/* Song catalog extracted from index.html for easier updates. */
var VOLUMES = [
  { name: 'Dance Floor',      emoji: '💃', desc: 'Cha-cha, disco, bachata & dance floor beats' },
  { name: 'Heart & Soul',     emoji: '💘', desc: 'Chill, bossa nova, deep emotion & longing'  },
  { name: 'Romantic Ballads', emoji: '💖', desc: 'Classic love songs, devotion & forever'      },
  { name: 'English Love',     emoji: '✨', desc: 'English romantic anthems'                    },
  { name: 'English Soul',     emoji: '🌙', desc: 'Introspective English stories'               },
  { name: 'Sundries',         emoji: '🗂️', desc: 'Songs that don\'t fit neatly elsewhere'     },
];

var SONGS = [
  // ── Vol 0: Cha-Cha & Disco ─────────────────────────────────────
  { title: "Asim Cha-Cha",                      file: "Asim Cha-Cha.mp3",                       lang: 'tl',  volIdx: 0 },
  { title: "Already Enough (Merengue)",         file: "Already Enough (Merengue).mp3",          lang: 'en',  volIdx: 0, added: '2026-04-13' },
  { title: "Already Enough (Salsa)",            file: "Already Enough (Salsa).mp3",             lang: 'en',  volIdx: 0, added: '2026-04-13' },
  { title: "Aslom Cha-Cha",                     file: "Aslom Cha-Cha.mp3",                      lang: 'ceb', volIdx: 0 },
  { title: "Batchata Queen",                    file: "Batchata Queen.mp3",                     lang: 'en',  volIdx: 0 },
  { title: "Cha-Cha Queen",                     file: "Cha-Cha Queen.mp3",                      lang: 'en',  volIdx: 0 },
  { title: "Hataw, Galaw",                      file: "Hataw, Galaw.mp3",          duration: "3:30", lang: 'tl', volIdx: 0 },
  { title: "Ikaw Ang Lahat Sa Akin",            file: "Ikaw Ang Lahat Sa Akin (Cha-Cha).mp3",   lang: 'tl',  volIdx: 0 },
  { title: "Ikaw Ang Lahat Sa Akin (Disco)",    file: "Ikaw Ang Lahat Sa Akin (Disco).mp3",     lang: 'tl',  volIdx: 0 },
  { title: "Just You And Me (70s Disco)",       file: "Just You And Me (70s Disco).mp3",        lang: 'en',  volIdx: 0 },
  { title: "Just You And Me (Bachata)",         file: "Just You And Me (Bachata).mp3",          lang: 'en',  volIdx: 0 },
  { title: "Kahit Kulang Ang Money (Cha-Cha)",  file: "Kahit Kulang Ang Money (Cha-Cha).mp3",   lang: 'tl',  volIdx: 0 },
  { title: "Kahit Saan Pa Mapunta (Disco)",     file: "Kahit Saan Pa Mapunta  (Disco).mp3",     lang: 'tl',  volIdx: 0 },
  { title: "Ngayon (Disco)",                    file: "Ngayon (Disco).mp3",                     lang: 'tl',  volIdx: 0 },
  { title: "Sa Lahat Ng Taon",                  file: "Sa Lahat Ng Taon (Cha-Cha).mp3",         lang: 'tl',  volIdx: 0 },
  { title: "Sa Lahat Ng Taon (Funk Disco)",     file: "Sa Lahat Ng Taon (Funk Disco).mp3",      lang: 'tl',  volIdx: 0 },
  { title: "Sumasayaw Sa Alon (Disco)",         file: "Sumasayaw Sa Alon (Disco).mp3",          lang: 'tl',  volIdx: 0 },
  { title: "Tara Na Sa Dagat",                  file: "Tara Na Sa Dagat.mp3",                   lang: 'tl',  volIdx: 0 },
  { title: "Tara Na Sa Dagat (Bachata)",        file: "Tara Na Sa Dagat (Bachata).mp3",         lang: 'tl',  volIdx: 0 },
  { title: "Hantungan (Manila Sound)",          file: "Hantungan (Manila Sound).mp3",           lang: 'tl',  volIdx: 0 },

  // ── Vol 1: Dance Floor ─────────────────────────────────────────
  { title: "Dance Partner",                     file: "Dance Partner.mp3",                      lang: 'en',  volIdx: 0 },
  { title: "Dance Some More",                   file: "Dance Some More.mp3",                    lang: 'en',  volIdx: 0 },
  { title: "Dancing Through The Years",         file: "Dancing Through The Years.mp3",          lang: 'en',  volIdx: 0 },
  { title: "Dancing With The Tide",             file: "Dancing With The Tide.mp3",              lang: 'en',  volIdx: 0 },
  { title: "Dancing With The Tide (Merengue)",  file: "Dancing With The Tide (Merengue).mp3",   lang: 'en',  volIdx: 0, added: '2026-04-13' },
  { title: "Kasayaw Ko Habang-Buhay",           file: "Kasayaw Ko Habang-Buhay.mp3", duration: "3:30", lang: 'tl', volIdx: 0 },
  { title: "Sayaw ng Puso",                     file: "Sayaw ng Puso.mp3",          duration: "3:36", lang: 'tl', volIdx: 0 },
  { title: "Sayaw Ng Puso (Funk-Pop)",          file: "Sayaw Ng Puso (Funk-Pop).mp3",           lang: 'tl',  volIdx: 0 },
  { title: "Sayaw Pa Tayo",                     file: "Sayaw Pa Tayo.mp3",          duration: "3:30", lang: 'tl', volIdx: 0 },
  { title: "Sumasayaw sa Alon",                 file: "Sumasayaw sa Alon.mp3",                  lang: 'tl',  volIdx: 0 },
  { title: "With You",                          file: "With You.mp3",                           lang: 'en',  volIdx: 0, added: '2026-04-10' },
  { title: "Busy at Sexy",                       file: "Busy at Sexy.mp3",                       lang: 'tl',  volIdx: 0 },
  { title: "Dancing With The Tide (Salsa)",      file: "Dancing With The Tide (Salsa).mp3",      lang: 'en',  volIdx: 0 },
  { title: "Flames in the Dark Room (Dance Synth)", file: "Flames in the Dark Room (Dance Synth).mp3", lang: 'en', volIdx: 0 },
  { title: "Flames in the Dark Room (Pop)",      file: "Flames in the Dark Room (Pop).mp3",      lang: 'en',  volIdx: 0 },
  { title: "Just You And Me (Salsa)",            file: "Just You And Me (Salsa).mp3",            lang: 'en',  volIdx: 0 },
  { title: "Just You And Me (Merengue)",         file: "Just You And Me (Merengue).mp3",         lang: 'en',  volIdx: 0, added: '2026-04-13' },
  { title: "Your Sanctuary (Disco)",             file: "Your Sanctuary (Disco).mp3",             lang: 'en',  volIdx: 0 },
  { title: "Dance Partner (Pop - Hip Hop)",      file: "Dance Partner (Pop - Hip Hop).mp3",      lang: 'en',  volIdx: 0 },
  { title: "Dance Some More (Reggae)",           file: "Dance Some More (Reggae).mp3",           lang: 'en',  volIdx: 5 },
  { title: "Dancing Through The Years (Salsa)",  file: "Dancing Through The Years (Salsa).mp3",  lang: 'en',  volIdx: 0 },
  { title: "I Wrote The Mountains (Bachata)",    file: "I Wrote The Mountains (Bachata).mp3",    lang: 'en',  volIdx: 0, added: '2026-04-08' },
  { title: "I Wrote The Mountains (Bossa)",      file: "I Wrote The Mountains (Bossa).mp3",      lang: 'en',  volIdx: 1, added: '2026-04-08' },
  { title: "I Wrote The Mountains (Cha-Cha)",    file: "I Wrote The Mountains (Cha-Cha).mp3",    lang: 'en',  volIdx: 0, added: '2026-04-08' },
  { title: "I Wrote The Mountains (Disco)",      file: "I Wrote The Mountains (Disco).mp3",      lang: 'en',  volIdx: 0, added: '2026-04-08' },
  { title: "I Wrote The Mountains (Salsa)",      file: "I Wrote The Mountains (Salsa).mp3",      lang: 'en',  volIdx: 0, added: '2026-04-08' },
  { title: "Gisulat Ko Ang Bukid (Disco)",       file: "Gisulat Ko Ang Bukid (Disco).mp3",       lang: 'ceb', volIdx: 0, added: '2026-04-09' },
  { title: "Gisulat Ko Ang Bukid (Salsa)",       file: "Gisulat Ko Ang Bukid (Salsa).mp3",       lang: 'ceb', volIdx: 1, added: '2026-04-09' },
  { title: "Kasayaw Ko Habang-Buhay (Disco)",    file: "Kasayaw Ko Habang-Buhay (Disco).mp3",    lang: 'tl',  volIdx: 0 },
  { title: "Nag-Anod Ta (Cha-Cha)",              file: "Nag-Anod Ta (Cha-Cha).mp3",              lang: 'ceb', volIdx: 0, added: '2026-04-10' },
  { title: "Nag-Anod Ta (Salsa)",                file: "Nag-Anod Ta (Salsa).mp3",                lang: 'ceb', volIdx: 0, added: '2026-04-10' },
  { title: "Payong (Dance)",                     file: "Payong (Dance).mp3",                      lang: 'tl',  volIdx: 0, added: '2026-04-09' },
  { title: "Sayaw Pa Tayo (Disco)",              file: "Sayaw Pa Tayo (Disco).mp3",              lang: 'tl',  volIdx: 0 },
  { title: "Sayaw Pa Tayo (Merengue)",           file: "Sayaw Pa Tayo (Merengue).mp3",           lang: 'tl',  volIdx: 0, added: '2026-04-13' },
  { title: "Silver Moon (Bachata)",              file: "Silver Moon (Bachata).mp3",              lang: 'en',  volIdx: 0, added: '2026-04-13' },
  { title: "Silver Moon (Cha-Cha)",              file: "Silver Moon (Cha-Cha).mp3",              lang: 'en',  volIdx: 0, added: '2026-04-13' },
  { title: "Silver Moon (Merengue)",             file: "Silver Moon (Merengue).mp3",             lang: 'en',  volIdx: 0, added: '2026-04-13' },
  { title: "Sumasayaw Sa Alon (Disco 2)",        file: "Sumasayaw Sa Alon (Disco 2).mp3",        lang: 'tl',  volIdx: 0 },
  { title: "We Keep Dancing (Bachata 2)",       file: "We Keep Dancing (Bachata 2).mp3",        lang: 'en',  volIdx: 0 },
  { title: "We Keep Dancing (Batchata)",        file: "We Keep Dancing (Batchata).mp3",         lang: 'en',  volIdx: 0 },
  { title: "We Keep Dancing",                   file: "We Keep Dancing (Cha-Cha).mp3",          lang: 'en',  volIdx: 0 },

  // ── Vol 2: Chill & Bossa ───────────────────────────────────────
  { title: "Beneath the Silver Moon",           file: "Beneath the Silver Moon.mp3",            lang: 'en',  volIdx: 3 },
  { title: "Beneath the Silver Moon (Chill)",   file: "Beneath the Silver Moon (Chill).mp3",    lang: 'en',  volIdx: 3 },
  { title: "Beneath the Silver Moon (Chill2)",  file: "Beneath the Silver Moon (Chill2).mp3",   lang: 'en',  volIdx: 3 },
  { title: "Drifting",                          file: "Drifting.mp3",                           lang: 'en',  volIdx: 3 },
  { title: "Drifting (Chill)",                  file: "Drifting (Chill).mp3",                   lang: 'en',  volIdx: 4 },
  { title: "Golden Hour Horizon",               file: "Golden Hour Horizon.mp3",                lang: 'en',  volIdx: 3 },
  { title: "Golden Hour Horizon (Bossa)",       file: "Golden Hour Horizon (Bossa).mp3",        lang: 'en',  volIdx: 4 },
  { title: "Isang Sulyap",                      file: "Isang Sulyap.mp3",                       lang: 'tl',  volIdx: 1 },
  { title: "Isang Sulyap (Bossa)",              file: "Isang Sulyap (Bossa).mp3",               lang: 'tl',  volIdx: 1 },
  { title: "Ocean",                             file: "Ocean.mp3",                  duration: "3:30", lang: 'en', volIdx: 4 },
  { title: "Ocean (Chill)",                     file: "Ocean (Chill).mp3",                      lang: 'en',  volIdx: 4 },
  { title: "Sa Lahat Ng Taon (Bossa)",          file: "Sa Lahat Ng Taon (Bossa).mp3",           lang: 'tl',  volIdx: 1 },
  { title: "Sailing",                           file: "Sailing.mp3",                            lang: 'en',  volIdx: 0 },
  { title: "Sailing (Bossa)",                   file: "Sailing (Bossa).mp3",                    lang: 'en',  volIdx: 4 },
  { title: "Same Horizon",                      file: "Same Horizon.mp3",                       lang: 'en',  volIdx: 4 },
  { title: "Same Horizon (Line)",               file: "Same Horizon Line.mp3",                  lang: 'en',  volIdx: 4 },
  { title: "Slow Time",                         file: "Slow  Time.mp3",             duration: "3:30", lang: 'en', volIdx: 3 },
  { title: "Slow Time (Chill)",                 file: "Slow Time (Chill).mp3",                  lang: 'en',  volIdx: 4 },
  { title: "Still Shining",                     file: "Still Shining.mp3",                      lang: 'en',  volIdx: 4 },
  { title: "Still Shining (Chill)",             file: "Still Shining (Chill).mp3",              lang: 'en',  volIdx: 4 },
  { title: "Warmth We Carry",                   file: "Warmth We Carry.mp3",                    lang: 'en',  volIdx: 3 },
  { title: "Warmth We Carry (Bossa)",           file: "Warmth We Carry (Bossa).mp3",            lang: 'en',  volIdx: 3 },
  { title: "Balas Ug Hangin",                   file: "Balas Ug Hangin.mp3",                    lang: 'ceb', volIdx: 1 },
  { title: "Hindi Ka Nag-Iisa",                 file: "Hindi Ka Nag-Iisa.mp3",                  lang: 'tl',  volIdx: 1 },
  { title: "Kasama Mo Ako",                     file: "Kasama Mo Ako.mp3",                      lang: 'tl',  volIdx: 1 },
  { title: "Through Every Trial",               file: "Through Every Trial.mp3",                lang: 'en',  volIdx: 4 },
  { title: "Pahulayan",                         file: "Pahulayan.mp3",              duration: "3:30", lang: 'ceb', volIdx: 1 },

  // ── Vol 3: Romantic Ballads ────────────────────────────────────
  { title: "Aking Hantungan",                   file: "Aking Hantungan.mp3",        duration: "4:10", lang: 'tl', volIdx: 2 },
  { title: "Bisan Layo Ka (Acoustic)",          file: "Bisan Layo Ka (Acoustic).mp3",           lang: 'ceb', volIdx: 2, added: '2026-04-06' },
  { title: "Daloy ng Pag-Ibig",                 file: "Daloy ng Pag-Ibig.mp3",                  lang: 'tl',  volIdx: 2 },
  { title: "Dito Ka Sa Akin",                   file: "Dito Ka Sa AKin.mp3",        duration: "3:30", lang: 'tl', volIdx: 2 },
  { title: "Hanggang sa Huli",                  file: "Hanggang sa Huli.mp3",       duration: "3:16", lang: 'tl', volIdx: 2 },
  { title: "Hanggang Sa Huli (Ballad)",         file: "Hanggang Sa Huli (Ballad).mp3",          lang: 'tl',  volIdx: 2 },
  { title: "Hanggang Sa Huli (Duet)",           file: "Hanggang Sa Huli (Duet).mp3",            lang: 'tl',  volIdx: 2 },
  { title: "Hanggang Sa Huli (R&B)",            file: "Hanggang Sa Huli (R&B).mp3",             lang: 'tl',  volIdx: 1 },
  { title: "Hanggang Sa Huli (R&B Ver2)",       file: "Hanggang Sa Huli (R&B Ver2).mp3",        lang: 'tl',  volIdx: 1 },
  { title: "Hawakan Ang Ngayon",                file: "Hawakan Ang Ngayon.mp3",     duration: "3:30", lang: 'tl', volIdx: 2 },
  { title: "Iisang Guhit",                      file: "Iisang Guhit.mp3",                       lang: 'tl',  volIdx: 2 },
  { title: "Ikaw ang Alon",                     file: "Ikaw ang Alon.mp3",          duration: "3:32", lang: 'tl', volIdx: 2 },
  { title: "Ikaw Ang Alon (Soul, R&B)",         file: "Ikaw Ang Alon (Soul, R&B).mp3",          lang: 'tl',  volIdx: 1 },
  { title: "Ikaw Ang Lahat Sa Akin",            file: "Ikaw Ang Lahat Sa Akin.mp3",             lang: 'tl',  volIdx: 2 },
  { title: "Ikaw Ang Tahanan",                  file: "Ikaw Ang Tahanan.mp3",       duration: "2:16", lang: 'tl', volIdx: 2 },
  { title: "Ikaw Ang Umaga",                    file: "Ikaw Ang Umaga.mp3",                     lang: 'tl',  volIdx: 2 },
  { title: "Ikaw Pa Rin",                       file: "Ikaw Pa Rin.mp3",            duration: "3:30", lang: 'tl', volIdx: 2 },
  { title: "Ikaw Pa Rin (Pop)",                 file: "Ikaw Pa Rin (Pop).mp3",                  lang: 'tl',  volIdx: 2 },
  { title: "Ikaw Pa Rin (Pop Ver2)",            file: "Ikaw Pa Rin (Pop Ver2).mp3",             lang: 'tl',  volIdx: 2 },
  { title: "Kislap sa Dilim",                   file: "Kislap sa Dilim.mp3",                    lang: 'tl',  volIdx: 2 },
  { title: "Gisulat Ko Ang Bukid",              file: "Gisulat Ko Ang Bukid.mp3",               lang: 'ceb', volIdx: 2, added: '2026-04-09' },
  { title: "Ilalom Sa Payong",                  file: "Ilalom Sa Payong.mp3",                   lang: 'ceb', volIdx: 1, added: '2026-04-09' },
  { title: "Ulan O Init",                       file: "Ulan O Init.mp3",                        lang: 'ceb', volIdx: 2, added: '2026-04-10' },
  { title: "Himig Ng Ating Kahapon",            file: "Himig Ng Ating Kahapon (Pop).mp3",       lang: 'tl',  volIdx: 2 },
  { title: "Himig Ng Ating Kahapon (Pop Ver2)", file: "Himig Ng Ating Kahapon (Pop Ver2).mp3",  lang: 'tl',  volIdx: 2 },
  { title: "Tahanan",                           file: "Tahanan.mp3",                            lang: 'tl',  volIdx: 2 },
  { title: "Tahanan (Ver 2)",                   file: "Tahanan (Ver 2).mp3",                    lang: 'tl',  volIdx: 2 },
  { title: "Tahanan (R&B Funky)",               file: "Tahanan (R&B Funky).mp3",                lang: 'tl',  volIdx: 1 },
  { title: "Tahanan (R&B Funky Ver2)",          file: "Tahanan (R&B Funky Ver2).mp3",           lang: 'tl',  volIdx: 1 },

  // ── Vol 4: Heart & Soul ────────────────────────────────────────
  { title: "Ania Ako",                          file: "Ania Ako.mp3",                           lang: 'ceb', volIdx: 1 },
  { title: "Ania Ako (R&B)",                    file: "Ania Ako (R&B).mp3",                     lang: 'ceb', volIdx: 1 },
  { title: "Ania Ako (Soul)",                   file: "Ania Ako (Soul).mp3",                    lang: 'ceb', volIdx: 1 },
  { title: "Bisan Layo Ka (R&B)",               file: "Bisan Layo Ka (R&B).mp3",                lang: 'ceb', volIdx: 1, added: '2026-04-06' },
  { title: "Dagat at Baybayin",                 file: "Dagat at Baybayin.mp3",                  lang: 'tl',  volIdx: 1 },
  { title: "Dagat at Baybayin (Male)",          file: "Dagat at Baybayin (Male).mp3",           lang: 'tl',  volIdx: 1 },
  { title: "Hindi Ka Dead Star",                file: "Hindi Ka Dead Star.mp3",     duration: "3:30", lang: 'tl', volIdx: 1 },
  { title: "Ibang Daan",                        file: "Ibang Daan.mp3",             duration: "3:39", lang: 'tl', volIdx: 1 },
  { title: "Isang Linggo Lang",                 file: "Isang Linggo Lang.mp3",      duration: "3:58", lang: 'tl', volIdx: 1 },
  { title: "Isang Linggo Lang (Pop)",           file: "Isang Linggo (Pop).mp3",                 lang: 'tl',  volIdx: 1 },
  { title: "Isang Linggo Lang (Pop Ver2)",      file: "Isang Linggo (Pop Ver2).mp3",            lang: 'tl',  volIdx: 1 },
  { title: "Hanggang Kailan",                   file: "Hanggang Kailan.mp3",                    lang: 'tl',  volIdx: 1, added: '2026-04-06' },
  { title: "Gisulat Ko Ang Bukid (Duet)",       file: "Gisulat Ko Ang Bukid (Duet).mp3",        lang: 'ceb', volIdx: 1, added: '2026-04-09' },
  { title: "I Wrote The Mountains (Jazz)",      file: "I Wrote The Mountains (Jazz).mp3",       lang: 'en',  volIdx: 1, added: '2026-04-08' },
  { title: "Ilalim Ng Payong (Indie Pop)",      file: "Ilalim Ng Payong (Indie Pop).mp3",       lang: 'tl',  volIdx: 1, added: '2026-04-09' },
  { title: "Ilalim ng Payong (R&B)",            file: "Ilalim ng Payong (R&B).mp3",             lang: 'tl',  volIdx: 1, added: '2026-04-09' },
  { title: "Ilalom Sa Payong (R&B)",            file: "Ilalom Sa Payong (R&B).mp3",             lang: 'ceb', volIdx: 1, added: '2026-04-09' },
  { title: "Kahit Saan Pa Mapunta",             file: "Kahit Saan Pa Mapunta.mp3",              lang: 'tl',  volIdx: 1 },
  { title: "Kahit Ulan O Araw",                 file: "Kahit Ulan O Araw.mp3",                  lang: 'tl',  volIdx: 1 },
  { title: "Kay Layo Mo Man",                   file: "Kay Layo Mo Man.mp3",                    lang: 'tl',  volIdx: 1, added: '2026-04-06' },
  { title: "Liyab sa Dilim",                    file: "Liyab sa Dilim.mp3",                     lang: 'tl',  volIdx: 1 },
  { title: "Magkasama",                         file: "Magkasama.mp3",                          lang: 'tl',  volIdx: 1 },
  { title: "Magkasama (R&B-Pop)",               file: "Magkasama (R&B-Pop).mp3",                lang: 'tl',  volIdx: 1 },
  { title: "Magkasama (Tayo Lagi)",             file: "Magkasama Tayo Lagi.mp3",                lang: 'tl',  volIdx: 1 },
  { title: "Mahalaga Nandito Ka",               file: "Mahalaga Nandito Ka.mp3",    duration: "3:55", lang: 'tl', volIdx: 1 },
  { title: "Morning Rain",                      file: "Morning Rain.mp3",                       lang: 'en',  volIdx: 1, added: '2026-04-04' },
  { title: "Muli",                              file: "Muli.mp3",                   duration: "3:30", lang: 'tl', volIdx: 0 },
  { title: "Nagbabalik",                        file: "Nagbabalik.mp3",                         lang: 'tl',  volIdx: 1 },
  { title: "Ulan O Init (Bossa)",               file: "Ulan O Init (Bossa).mp3",                lang: 'ceb', volIdx: 1, added: '2026-04-10' },
  { title: "Ulan O Init (2)",                   file: "Ulan O Init (2).mp3",                    lang: 'ceb', volIdx: 1, added: '2026-04-10' },
  { title: "Payong (Duet)",                     file: "Payong (Duet).mp3",                      lang: 'tl',  volIdx: 1, added: '2026-04-09' },
  { title: "Himig Ng Ating Kahapon (R&B Funky)", file: "Himig Ng Ating Kahapon (R&B Funky).mp3", lang: 'tl',  volIdx: 1 },

  // ── Vol 5: Devotion ────────────────────────────────────────────
  { title: "Dito Ka Sa Akin (Synth-Pop)",        file: "Dito Ka Sa AKin (Synth-Pop).mp3",        lang: 'tl',  volIdx: 2 },
  { title: "Dito Ka Sa Akin (Synth-Pop2)",       file: "Dito Ka Sa AKin (Synth-Pop2).mp3",       lang: 'tl',  volIdx: 2 },
  { title: "Habang Tumatagal",                   file: "Habang Tumatagal.mp3",       duration: "3:30", lang: 'tl', volIdx: 2 },
  { title: "Habang Tumatagal (R&B)",             file: "Habang Tumatagal (R&B).mp3",             lang: 'tl',  volIdx: 2 },
  { title: "Hawakan Ang Ngayon (Synth-Pop)",     file: "Hawakan Ang Ngayon (Synth-Pop).mp3",     lang: 'tl',  volIdx: 2 },
  { title: "Hawakan Ang Ngayon (Synth-Pop2)",    file: "Hawakan Ang Ngayon (Synth-Pop2).mp3",    lang: 'tl',  volIdx: 2 },
  { title: "Ito Tayo",                          file: "Ito Tayo.mp3",                           lang: 'tl',  volIdx: 2 },
  { title: "Kanlungan",                         file: "Kanlungan.mp3",              duration: "3:30", lang: 'tl', volIdx: 2 },
  { title: "Kung Nandito Ka Sana",              file: "Kung Nandito Ka Sana.mp3",   duration: "3:30", lang: 'tl', volIdx: 2 },
  { title: "Muling Humihinga",                  file: "Muling Humihinga.mp3",                   lang: 'tl',  volIdx: 2 },
  { title: "Nanatiling Bakas",                  file: "Nanatiling Bakas.mp3",       duration: "3:43", lang: 'tl', volIdx: 2 },
  { title: "Nandito Ako",                       file: "Nandito Ako.mp3",                        lang: 'tl',  volIdx: 2 },
  { title: "Nandito Ako (Nu-Jazz)",             file: "Nandito Ako (Nu-Jazz).mp3",              lang: 'tl',  volIdx: 2 },
  { title: "Payong (Acoustic)",                 file: "Payong (Acoustic).mp3",                  lang: 'tl',  volIdx: 2, added: '2026-04-09' },
  { title: "Payong (Ballad)",                   file: "Payong (Ballad).mp3",                    lang: 'tl',  volIdx: 2, added: '2026-04-09' },
  { title: "Payong (Duet 2)",                   file: "Payong (Duet 2).mp3",                    lang: 'tl',  volIdx: 2, added: '2026-04-09' },
  { title: "Payong (Solo)",                     file: "Payong (Solo).mp3",                      lang: 'tl',  volIdx: 2, added: '2026-04-09' },
  { title: "Sa Dilim, Ikaw at Ako",             file: "Sa Dilim, Ikaw at Ako.mp3",  duration: "3:30", lang: 'tl', volIdx: 2 },
  { title: "Sa Ilalim ng Payong",               file: "Sa Ilalim ng Payong.mp3",    duration: "3:30", lang: 'tl', volIdx: 2 },
  { title: "Sa Maulang Biyahe",                 file: "Sa Maulang Biyahe.mp3",                  lang: 'tl',  volIdx: 2 },
  { title: "Sa Lahat Ng Taon",                  file: "Sa Lahat Ng Taon.mp3",                   lang: 'tl',  volIdx: 2 },
  { title: "Sa Tabing Dagat",                   file: "Sa Tabing Dagat.mp3",        duration: "3:30", lang: 'tl', volIdx: 2 },
  { title: "Sa Yakap Mo",                       file: "Sa Yakap Mo.mp3",            duration: "3:30", lang: 'tl', volIdx: 2 },
  { title: "Sapat Na",                          file: "Sapat Na.mp3",                           lang: 'tl',  volIdx: 2 },
  { title: "Tadhana",                           file: "Tadhana.mp3",                duration: "3:30", lang: 'tl', volIdx: 2 },
  { title: "Tadhana (Male)",                    file: "Tadhana (Male).mp3",                     lang: 'tl',  volIdx: 2 },
  { title: "Tanging Yaman",                     file: "Tanging Yaman.mp3",          duration: "3:30", lang: 'tl', volIdx: 2 },

  // ── Vol 6: English Love ────────────────────────────────────────
  { title: "Always",                            file: "Always.mp3",                             lang: 'en',  volIdx: 3 },
  { title: "Already Enough (Ballad)",           file: "Already Enough (Ballad).mp3",            lang: 'en',  volIdx: 3, added: '2026-04-13' },
  { title: "Always (UK House)",                 file: "Always (UK House).mp3",                  lang: 'en',  volIdx: 3 },
  { title: "Always You",                        file: "Always You.mp3",                         lang: 'en',  volIdx: 3 },
  { title: "As Time Goes On (UK House)",        file: "As Time Goes On (UK House).mp3",         lang: 'en',  volIdx: 3 },
  { title: "Because of You",                    file: "Because of You.mp3",                     lang: 'en',  volIdx: 3 },
  { title: "Between Us",                        file: "Between Us.mp3",                         lang: 'en',  volIdx: 3 },
  { title: "Coming Back to You",                file: "Coming Back to You.mp3",                 lang: 'en',  volIdx: 3 },
  { title: "Every Season (Pop-Soul)",           file: "Every Season (Pop-Soul).mp3",            lang: 'en',  volIdx: 3 },
  { title: "Forever You",                       file: "Forever You.mp3",                        lang: 'en',  volIdx: 3 },
  { title: "I Am Yours",                        file: "I Am Yours.mp3",                         lang: 'en',  volIdx: 3 },
  { title: "I Found You Again",                 file: "I Found You Again.mp3",                  lang: 'en',  volIdx: 3 },
  { title: "I Love You More",                   file: "I Love You More.mp3",                    lang: 'en',  volIdx: 3 },
  { title: "I Wrote The Mountains (Acoustic)",  file: "I Wrote The Mountains (Acoustic).mp3",   lang: 'en',  volIdx: 3, added: '2026-04-08' },
  { title: "I'll Hold The Line",                file: "I'll Hold The Line.mp3",     duration: "3:30", lang: 'en', volIdx: 3 },
  { title: "I'm Gonna Love You",                file: "I'm Gonna Love You.mp3",                 lang: 'en',  volIdx: 3 },
  { title: "In Your Embrace",                   file: "In Your Embrace.mp3",                    lang: 'en',  volIdx: 3 },
  { title: "Intertwined",                       file: "Intertwined.mp3",                        lang: 'en',  volIdx: 3 },
  { title: "It's You",                          file: "It's You.mp3",               duration: "3:30", lang: 'en', volIdx: 3 },
  { title: "Just Stay With Me",                 file: "Just Stay With Me.mp3",                  lang: 'en',  volIdx: 3 },
  { title: "My Safe Place (Chill)",             file: "My Safe Place (Chill).mp3",              lang: 'en',  volIdx: 3, added: '2026-04-04' },
  { title: "Now Intertwined",                   file: "Now Intertwined.mp3",                    lang: 'en',  volIdx: 3 },
  { title: "Together, Always",                  file: "Together, Always.mp3",                   lang: 'en',  volIdx: 3 },

  // ── Vol 7: English Soul ────────────────────────────────────────
  { title: "As Time Goes On",                   file: "As Time Goes On.mp3",                    lang: 'en',  volIdx: 3 },
  { title: "Already Enough",                    file: "Already Enough.mp3",                     lang: 'en',  volIdx: 4, added: '2026-04-13' },
  { title: "Before I Healed",                   file: "Before I Healed.mp3",                    lang: 'en',  volIdx: 4, added: '2026-04-05' },
  { title: "Before The Light",                  file: "Before The Light.mp3",                   lang: 'en',  volIdx: 4, added: '2026-04-05' },
  { title: "Dead Star",                         file: "Dead Star.mp3",                          lang: 'en',  volIdx: 4 },
  { title: "Flames",                            file: "Flames.mp3",                             lang: 'en',  volIdx: 4 },
  { title: "Flames (in the Dark Room)",         file: "Flames in the Dark Room.mp3",            lang: 'en',  volIdx: 4 },
  { title: "Home",                              file: "Home.mp3",                               lang: 'en',  volIdx: 4 },
  { title: "I Wrote The Mountains",             file: "I Wrote The Mountains.mp3",              lang: 'en',  volIdx: 4, added: '2026-04-08' },
  { title: "Maybe Happy Ending",                file: "Maybe Happy Ending.mp3",                 lang: 'en',  volIdx: 4 },
  { title: "My Safe Place",                     file: "My Safe Place.mp3",                      lang: 'en',  volIdx: 0 },
  { title: "Not A Reward",                      file: "Not A Reward.mp3",                       lang: 'en',  volIdx: 4, added: '2026-04-05' },
  { title: "Not So Bad Afterall",               file: "Not So Bad Afterall.mp3",                lang: 'en',  volIdx: 4 },
  { title: "Not So Bad Afterall (Indie)",       file: "Not So Bad Afterall (Indie).mp3",        lang: 'en',  volIdx: 4 },
  { title: "Old and Gray",                      file: "Old and Gray.mp3",                       lang: 'en',  volIdx: 4 },
  { title: "Sanctuary",                         file: "Sanctuary.mp3",              duration: "3:30", lang: 'en', volIdx: 4 },
  { title: "Steady Hearts (Chill)",             file: "Steady Hearts (Chill).mp3",              lang: 'en',  volIdx: 4, added: '2026-04-04' },
  { title: "The Echo",                          file: "The Echo.mp3",                           lang: 'en',  volIdx: 4 },
  { title: "The Medicine of Us",                file: "The Medicine of Us.mp3",                 lang: 'en',  volIdx: 4, added: '2026-04-05' },
  { title: "The Rhythm of the Dark",            file: "The Rhythm of the Dark.mp3", duration: "3:30", lang: 'en', volIdx: 4 },
  { title: "The World You Chose",               file: "The World You Chose.mp3",    duration: "3:30", lang: 'en', volIdx: 4 },
  { title: "This Is Us",                        file: "This Is Us.mp3",                         lang: 'en',  volIdx: 4 },
  { title: "With You (2)",                      file: "With You (2).mp3",                       lang: 'en',  volIdx: 4, added: '2026-04-10' },
  { title: "As Time Goes On (Chill)",           file: "As Time Goes On (Chill).mp3",            lang: 'en',  volIdx: 4 },

  // ── (former Good Times — distributed) ────────────────────────
  { title: "Baka Ang Happy Ending",             file: "Baka Ang Happy Ending.mp3",              lang: 'tl',  volIdx: 1 },
  { title: "Baka Ang Saya",                     file: "Baka Ang Saya.mp3",                      lang: 'tl',  volIdx: 1 },
  { title: "Domestic Hustle",                   file: "Domestic Hustle.mp3",                    lang: 'en',  volIdx: 4 },
  { title: "Finally Home",                      file: "Finally Home.mp3",                       lang: 'en',  volIdx: 3 },
  { title: "Just You And Me",                   file: "Just You And Me.mp3",                    lang: 'en',  volIdx: 3 },
  { title: "My Grumpy, Old Honey",              file: "My Grumpy, Old Honey.mp3",               lang: 'en',  volIdx: 4 },
  { title: "Staycation Lang",                   file: "Staycation Lang.mp3",                    lang: 'tl',  volIdx: 1 },
  { title: "Staycation (R&B Funky)",            file: "Staycation (R&B Funky).mp3",             lang: 'tl',  volIdx: 1 },
  { title: "With You (Chill)",                  file: "With You (Chill).mp3",                   lang: 'en',  volIdx: 1, added: '2026-04-10' },
  { title: "Thank You, My Love",                file: "Thank You, My Love.mp3",                 lang: 'en',  volIdx: 3 },
  { title: "Thank You, My Love (Retro-Soul)",   file: "Thank You, My Love (Retro-Soul).mp3",    lang: 'en',  volIdx: 4 },
  { title: "This Time We're Staying",           file: "This Time We're Staying.mp3",            lang: 'en',  volIdx: 3 },
  { title: "In the Quiet Between Us",           file: "In the Quiet Between Us.mp3",            lang: 'en',  volIdx: 3 },
  { title: "In the Quiet Between Us (Bachata)", file: "In the Quiet Between Us (Bachata).mp3",  lang: 'en',  volIdx: 0 },
  { title: "Steady Hearts",                     file: "Steady Hearts.mp3",                      lang: 'en',  volIdx: 3 },
  { title: "Under This Umbrella",               file: "Under This Umbrella.mp3",                lang: 'en',  volIdx: 3 },
  { title: "You Are My Everything",             file: "You Are My Everything.mp3",              lang: 'en',  volIdx: 3 },
  { title: "With You (Pop-Rock)",               file: "With You (Pop-Rock).mp3",                lang: 'en',  volIdx: 3, added: '2026-04-10' },

  // ── Vol 9: Sundries ────────────────────────────────────────────
  { title: "Barkada",                           file: "Barkada.mp3",                            lang: 'tl',  volIdx: 5 },
  { title: "Barkada (Ver 2)",                   file: "Barkada (Ver 2).mp3",                    lang: 'tl',  volIdx: 5 },
  { title: "Panay Panalangin",                  file: "Panay Panalangin.mp3",                   lang: 'tl',  volIdx: 5 },
  { title: "Ako'y Lalaban",                     file: "Ako'y Lalaban.mp3",                      lang: 'tl',  volIdx: 5 },
  { title: "Steady Ascent",                     file: "Steady Ascent.mp3",                      lang: 'en',  volIdx: 5 },
  { title: "Steady Ascent (Indie Pop)",          file: "Steady Ascent (Indie Pop).mp3",          lang: 'en',  volIdx: 5 },
  { title: "Steady Ascent (Rock)",              file: "Steady Ascent (Rock).mp3",               lang: 'en',  volIdx: 5 },
  { title: "Trading Ice for Rain",              file: "Trading Ice for Rain.mp3",               lang: 'en',  volIdx: 5 },
  { title: "Trading Ice for Rain (R&B)",        file: "Trading Ice for Rain (R&B).mp3",         lang: 'en',  volIdx: 5 },
  { title: "Tropical Home",                      file: "Tropical Home.mp3",                      lang: 'en',  volIdx: 0, added: '2026-04-03' },
  { title: "Lost In The Beat",                  file: "Lost In The Beat.mp3",                   lang: 'en',  volIdx: 4, added: '2026-04-01' },
  { title: "Lost In The Beat (Disco)",          file: "Lost In The Beat (Disco).mp3",           lang: 'en',  volIdx: 0, added: '2026-04-01' },
  { title: "Lost In The Beat (R&B-Pop)",        file: "Lost In The Beat (R&B-Pop).mp3",         lang: 'en',  volIdx: 0, added: '2026-04-01' },
];
