/* Song catalog extracted from index.html for easier updates. */
var VOLUMES = [
  { name: 'Dance Floor',      emoji: '💃', desc: 'Cha-cha, disco, bachata & dance floor beats' },
  { name: 'Heart & Soul',     emoji: '💘', desc: 'Chill, bossa nova, deep emotion & longing'  },
  { name: 'Romantic Ballads', emoji: '💖', desc: 'Classic love songs, devotion & forever'      },
  { name: 'English Love',     emoji: '✨', desc: 'English romantic anthems'                    },
  { name: 'English Soul',     emoji: '🌙', desc: 'Introspective English stories'               },
  { name: 'Sundries',         emoji: '🗂️', desc: 'Songs that don\'t fit neatly elsewhere'     },
];

var SONGS = [
  // ── Vol 0: Cha-Cha & Disco ─────────────────────────────────────
  { title: "Asim Cha-Cha",                      file: "Asim Cha-Cha.mp3",                       lang: 'tl',  volIdx: 0 },
  { title: "Already Enough (Merengue)",         file: "Already Enough (Merengue).mp3",          lang: 'en',  volIdx: 0, added: '2026-04-13' },
  { title: "Already Enough (Salsa)",            file: "Already Enough (Salsa).mp3",             lang: 'en',  volIdx: 0, added: '2026-04-13' },
  { title: "Alon (Tango)",                      file: "Alon (Tango).mp3",                       lang: 'tl',  volIdx: 0, added: '2026-04-25' },
  { title: "Aslom Cha-Cha",                     file: "Aslom Cha-Cha.mp3",                      lang: 'ceb', volIdx: 0 },
  { title: "Bisan Layo Ka (M)",                 file: "Bisan Layo Ka (M).mp3",                  lang: 'ceb', volIdx: 0, added: '2026-04-19' },
  { title: "Bisan Layo Ka (S)",                 file: "Bisan Layo Ka (S).mp3",                  lang: 'ceb', volIdx: 0, added: '2026-04-19' },
  { title: "Before Its Gone (C)",               file: "Before Its Gone (C).mp3",                lang: 'en',  volIdx: 0, added: '2026-04-16' },
  { title: "Before Its Gone (D)",               file: "Before Its Gone (D).mp3",                lang: 'en',  volIdx: 0, added: '2026-04-16' },
  { title: "Before It's Gone (K-Pop)",          file: "Before It's Gone (K-Pop).mp3",           lang: 'en',  volIdx: 0, added: '2026-04-17' },
  { title: "Before It's Gone (Reggae)",         file: "Before It's Gone (Reggae).mp3",          lang: 'en',  volIdx: 0, added: '2026-04-17' },
  { title: "Batchata Queen",                    file: "Batchata Queen.mp3",                     lang: 'en',  volIdx: 0 },
  { title: "Cha-Cha Queen",                     file: "Cha-Cha Queen.mp3",                      lang: 'en',  volIdx: 0 },
  { title: "Hataw, Galaw",                      file: "Hataw, Galaw.mp3",          duration: "3:30", lang: 'tl', volIdx: 0 },
  { title: "Hataw, Galaw (B)",                  file: "Hataw, Galaw (B).mp3",                   lang: 'tl',  volIdx: 0, added: '2026-04-14' },
  { title: "Hataw, Galaw (C)",                  file: "Hataw, Galaw (C).mp3",                   lang: 'tl',  volIdx: 0, added: '2026-04-14' },
  { title: "Hataw, Galaw (M)",                  file: "Hataw, Galaw (M).mp3",                   lang: 'tl',  volIdx: 0, added: '2026-04-14' },
  { title: "Hataw, Galaw (S)",                  file: "Hataw, Galaw (S).mp3",                   lang: 'tl',  volIdx: 0, added: '2026-04-14' },
  { title: "Ikaw Ang Lahat Sa Akin",            file: "Ikaw Ang Lahat Sa Akin (Cha-Cha).mp3",   lang: 'tl',  volIdx: 0 },
  { title: "Ikaw Ang Lahat Sa Akin (Disco)",    file: "Ikaw Ang Lahat Sa Akin (Disco).mp3",     lang: 'tl',  volIdx: 0 },
  { title: "Just You And Me (70s Disco)",       file: "Just You And Me (70s Disco).mp3",        lang: 'en',  volIdx: 0 },
  { title: "Just You And Me (Bachata)",         file: "Just You And Me (Bachata).mp3",          lang: 'en',  volIdx: 0 },
  { title: "Kahit Kulang Ang Money (Cha-Cha)",  file: "Kahit Kulang Ang Money (Cha-Cha).mp3",   lang: 'tl',  volIdx: 5 },
  { title: "Kahit Saan Pa Mapunta (Disco)",     file: "Kahit Saan Pa Mapunta  (Disco).mp3",     lang: 'tl',  volIdx: 0 },
  { title: "Ngayon (Disco)",                    file: "Ngayon (Disco).mp3",                     lang: 'tl',  volIdx: 0 },
  { title: "Sa Lahat Ng Taon",                  file: "Sa Lahat Ng Taon (Cha-Cha).mp3",         lang: 'tl',  volIdx: 0 },
  { title: "Sa Lahat Ng Taon (Funk Disco)",     file: "Sa Lahat Ng Taon (Funk Disco).mp3",      lang: 'tl',  volIdx: 0 },
  { title: "Sumasayaw Sa Alon (Disco)",         file: "Sumasayaw Sa Alon (Disco).mp3",          lang: 'tl',  volIdx: 0 },
  { title: "Tara Na Sa Dagat",                  file: "Tara Na Sa Dagat.mp3",                   lang: 'tl',  volIdx: 5 },
  { title: "Tara Na Sa Dagat (Bachata)",        file: "Tara Na Sa Dagat (Bachata).mp3",         lang: 'tl',  volIdx: 0 },
  { title: "Hantungan (Manila Sound)",          file: "Hantungan (Manila Sound).mp3",           lang: 'tl',  volIdx: 0 },

  // ── Vol 1: Dance Floor ─────────────────────────────────────────
  { title: "Dance Partner",                     file: "Dance Partner.mp3",                      lang: 'en',  volIdx: 0 },
  { title: "Dance Some More",                   file: "Dance Some More.mp3",                    lang: 'en',  volIdx: 0 },
  { title: "Dancing Through The Years",         file: "Dancing Through The Years.mp3",          lang: 'en',  volIdx: 0 },
  { title: "Dancing With The Tide",             file: "Dancing With The Tide.mp3",              lang: 'en',  volIdx: 0 },
  { title: "Dancing With The Tide (Merengue)",  file: "Dancing With The Tide (Merengue).mp3",   lang: 'en',  volIdx: 0, added: '2026-04-13' },
  { title: "Dance With Me (Salsa)",             file: "Dance With Me (Salsa).mp3",              lang: 'en',  volIdx: 0, added: '2026-04-27' },
  { title: "Dead Star (Tango)",                 file: "Dead Star (Tango).mp3",                  lang: 'en',  volIdx: 0, added: '2026-04-25' },
  { title: "Desire (Tango)",                    file: "Desire (Tango).mp3",                     lang: 'en',  volIdx: 0, added: '2026-04-27' },
  { title: "Dagat at Baybayin (Salsa)",         file: "Dagat at Baybayin (Salsa).mp3",          lang: 'tl',  volIdx: 0, added: '2026-04-21' },
  { title: "Dagat at Baybayin (Club Dance)",    file: "Dagat at Baybayin (Club Dance).mp3",     lang: 'tl',  volIdx: 0, added: '2026-04-23' },
  { title: "Baybayin (Tango)",                  file: "Baybayin (Tango).mp3",                   lang: 'tl',  volIdx: 0, added: '2026-04-25' },
  { title: "Disco Dream (Hustle)",              file: "Disco Dream (Hustle).mp3",               lang: 'en',  volIdx: 0, added: '2026-04-27' },
  { title: "Di Madaling Mahalin (EDM Dance)",   file: "Di Madaling Mahalin (EDM Dance).mp3",    lang: 'tl',  volIdx: 0, added: '2026-04-18' },
  { title: "Di Madaling Mahalin (K-Pop)",       file: "Di Madaling Mahalin (K-Pop).mp3",        lang: 'tl',  volIdx: 0, added: '2026-04-18' },
  { title: "Di Madaling Mahalin (Rave)",        file: "Di Madaling Mahalin (Rave).mp3",         lang: 'tl',  volIdx: 0, added: '2026-04-18' },
  { title: "Every Step (Merengue)",             file: "Every Step (Merengue).mp3",              lang: 'en',  volIdx: 0, added: '2026-04-27' },
  { title: "Faithful Hearts Bachata",           file: "Faithful Hearts Bachata.mp3",            lang: 'en',  volIdx: 0, added: '2026-04-20' },
  { title: "Faithful Hearts Cha-Cha",           file: "Faithful Hearts Cha-Cha.mp3",            lang: 'en',  volIdx: 0, added: '2026-04-20' },
  { title: "Faithful Hearts Merengue",          file: "Faithful Hearts Merengue.mp3",           lang: 'en',  volIdx: 0, added: '2026-04-20' },
  { title: "Faithful Hearts Salsa",             file: "Faithful Hearts Salsa.mp3",              lang: 'en',  volIdx: 0, added: '2026-04-20' },
  { title: "Faithful Hearts (Tango)",           file: "Fatithful Hearts (Tango).mp3",           lang: 'en',  volIdx: 0, added: '2026-04-25' },
  { title: "Flames (EDM Dance)",                file: "Flames (EDM Dance).mp3",                 lang: 'en',  volIdx: 0, added: '2026-04-18' },
  { title: "Flames (K-Pop)",                    file: "Flames (K-Pop).mp3",                     lang: 'en',  volIdx: 0, added: '2026-04-18' },
  { title: "Flames (Rave)",                     file: "Flames (Rave).mp3",                      lang: 'en',  volIdx: 0, added: '2026-04-18' },
  { title: "Gisulat Ko Ang Bukid (EDM Dance)",  file: "Gisulat Ko Ang Bukid (EDM Dance).mp3",   lang: 'ceb', volIdx: 0, added: '2026-04-18' },
  { title: "Gisulat Ko Ang Bukid (K-Pop)",      file: "Gisulat Ko Ang Bukid (K-Pop).mp3",       lang: 'ceb', volIdx: 0, added: '2026-04-18' },
  { title: "Gisulat Ko Ang Bukid (Rave)",       file: "Gisulat Ko Ang Bukid (Rave).mp3",        lang: 'ceb', volIdx: 0, added: '2026-04-18' },
  { title: "Hold Me Close (Bachata)",           file: "Hold Me Close (Bachata).mp3",            lang: 'en',  volIdx: 0, added: '2026-04-27' },
  { title: "Kasayaw Ko Habang-Buhay",           file: "Kasayaw Ko Habang-Buhay.mp3", duration: "3:30", lang: 'tl', volIdx: 0 },
  { title: "Sayaw ng Puso",                     file: "Sayaw ng Puso.mp3",          duration: "3:36", lang: 'tl', volIdx: 0 },
  { title: "Sayaw Ng Puso (Funk-Pop)",          file: "Sayaw Ng Puso (Funk-Pop).mp3",           lang: 'tl',  volIdx: 0 },
  { title: "Sayaw Pa Tayo",                     file: "Sayaw Pa Tayo.mp3",          duration: "3:30", lang: 'tl', volIdx: 0 },
  { title: "Sumasayaw sa Alon",                 file: "Sumasayaw sa Alon.mp3",                  lang: 'tl',  volIdx: 0 },
  { title: "With You",                          file: "With You.mp3",                           lang: 'en',  volIdx: 0, added: '2026-04-10' },
  { title: "With You (Rumba)",                  file: "With You (Rumba).mp3",                   lang: 'en',  volIdx: 0, added: '2026-04-25' },
  { title: "Busy at Sexy",                       file: "Busy at Sexy.mp3",                       lang: 'tl',  volIdx: 5 },
  { title: "Dancing With The Tide (Salsa)",      file: "Dancing With The Tide (Salsa).mp3",      lang: 'en',  volIdx: 0 },
  { title: "Flames in the Dark Room (Dance Synth)", file: "Flames in the Dark Room (Dance Synth).mp3", lang: 'en', volIdx: 0 },
  { title: "Flames in the Dark Room (Pop)",      file: "Flames in the Dark Room (Pop).mp3",      lang: 'en',  volIdx: 0 },
  { title: "Just You And Me (Salsa)",            file: "Just You And Me (Salsa).mp3",            lang: 'en',  volIdx: 0 },
  { title: "Just You And Me (Merengue)",         file: "Just You And Me (Merengue).mp3",         lang: 'en',  volIdx: 0, added: '2026-04-13' },
  { title: "Just You And Me (Rumba)",            file: "Just You And Me (Rumba).mp3",            lang: 'en',  volIdx: 0, added: '2026-04-25' },
  { title: "Just Because (Rumba)",              file: "Just Because (Rumba).mp3",               lang: 'en',  volIdx: 0, added: '2026-04-25' },
  { title: "Just Because (K-Pop)",              file: "Just Because (K-Pop).mp3",               lang: 'en',  volIdx: 0, added: '2026-04-17' },
  { title: "Your Sanctuary (Disco)",             file: "Your Sanctuary (Disco).mp3",             lang: 'en',  volIdx: 0 },
  { title: "Dance Partner (Pop - Hip Hop)",      file: "Dance Partner (Pop - Hip Hop).mp3",      lang: 'en',  volIdx: 0 },
  { title: "Dance Some More (Reggae)",           file: "Dance Some More (Reggae).mp3",           lang: 'en',  volIdx: 5 },
  { title: "Dancing Through The Years (Salsa)",  file: "Dancing Through The Years (Salsa).mp3",  lang: 'en',  volIdx: 0 },
  { title: "I Wrote The Mountains (Bachata)",    file: "I Wrote The Mountains (Bachata).mp3",    lang: 'en',  volIdx: 0, added: '2026-04-08' },
  { title: "I Wrote The Mountains (Bossa)",      file: "I Wrote The Mountains (Bossa).mp3",      lang: 'en',  volIdx: 1, added: '2026-04-08' },
  { title: "I Wrote The Mountains (Cha-Cha)",    file: "I Wrote The Mountains (Cha-Cha).mp3",    lang: 'en',  volIdx: 0, added: '2026-04-08' },
  { title: "I Wrote The Mountains (Disco)",      file: "I Wrote The Mountains (Disco).mp3",      lang: 'en',  volIdx: 0, added: '2026-04-08' },
  { title: "I Wrote The Mountains (Salsa)",      file: "I Wrote The Mountains (Salsa).mp3",      lang: 'en',  volIdx: 0, added: '2026-04-08' },
  { title: "Habang Tumatagal (Tango)",          file: "Habang Tumatagal (Tango).mp3",           lang: 'tl',  volIdx: 0, added: '2026-04-25' },
  { title: "Ikaw Ang Alon (Salsa)",             file: "Ikaw Ang Alon (Salsa).mp3",              lang: 'tl',  volIdx: 0, added: '2026-04-21' },
  { title: "Ikaw ang Alon (K-Pop)",             file: "Ikaw ang Alon (K-Pop).mp3",              lang: 'tl',  volIdx: 0, added: '2026-04-23' },
  { title: "Igo Na Kanako (Tango)",             file: "Igo Na Kanako (Tango).mp3",              lang: 'ceb', volIdx: 0, added: '2026-04-25' },
  { title: "In Your Eyes (Salsa)",              file: "In Your Eyes (Salsa).mp3",               lang: 'en',  volIdx: 0, added: '2026-04-23' },
  { title: "In Your Eyes (Synth Pop)",          file: "In Your Eyes (Synth Pop).mp3",           lang: 'en',  volIdx: 0, added: '2026-04-23' },
  { title: "Ilalim Ng Payong (M)",              file: "Ilalim Ng Payong (M).mp3",               lang: 'tl',  volIdx: 0, added: '2026-04-19' },
  { title: "Lost In The Beat (Cha-Cha)",         file: "Lost In The Beat (Cha-Cha).mp3",         lang: 'en',  volIdx: 0, added: '2026-04-13' },
  { title: "Lost In The Beat (K-Pop)",          file: "Lost In The Beat (K-Pop).mp3",           lang: 'en',  volIdx: 0, added: '2026-04-17' },
  { title: "Lost In The Beat (Merengue)",        file: "Lost In The Beat (Merengue).mp3",        lang: 'en',  volIdx: 0, added: '2026-04-13' },
  { title: "Lost In The Beat (Salsa)",           file: "Lost In The Beat (Salsa).mp3",           lang: 'en',  volIdx: 0, added: '2026-04-13' },
  { title: "Light In Your Eyes (Club Dance)",   file: "Light In Your Eyes (Club Dance).mp3",    lang: 'en',  volIdx: 0, added: '2026-04-23' },
  { title: "Light of Your Eyes (Salsa)",        file: "Light of Your Eyes (Salsa).mp3",         lang: 'en',  volIdx: 0, added: '2026-04-23' },
  { title: "Kanlungan (Rumba)",                 file: "Kanlungan (Rumba).mp3",                  lang: 'tl',  volIdx: 0, added: '2026-04-25' },
  { title: "Payong (Tango)",                    file: "Payong (Tango).mp3",                     lang: 'tl',  volIdx: 0, added: '2026-04-25' },
  { title: "Magkasama (Country)",               file: "Magkasama (Country).mp3",                lang: 'tl',  volIdx: 0, added: '2026-05-04' },
  { title: "My Once In A Lifetime (Country)",   file: "My Once In A Lifetime (Country).mp3",    lang: 'en',  volIdx: 0, added: '2026-05-04' },
  { title: "My Once In A Lifetime (Rumba)",     file: "My Once In A Lifetime (Rumba).mp3",      lang: 'en',  volIdx: 0, added: '2026-05-03' },
  { title: "My Once In A Lifetime (Tango)",     file: "My Once In A Lifetime (Tango).mp3",      lang: 'en',  volIdx: 0, added: '2026-05-03' },
  { title: "Paruparo (Hustle)",                 file: "Paruparo (Hustle).mp3",                  lang: 'tl',  volIdx: 0, added: '2026-05-03' },
  { title: "Paruparo (Merengue)",               file: "Paruparo (Merengue).mp3",                lang: 'tl',  volIdx: 0, added: '2026-05-03' },
  { title: "Paruparo Sa Balikat (Rumba)",       file: "Paruparo Sa Balikat (Rumba).mp3",        lang: 'tl',  volIdx: 0, added: '2026-05-03' },
  { title: "Pitong Araw (Tango)",               file: "Pitong Araw (Tango).mp3",                lang: 'tl',  volIdx: 0, added: '2026-04-25' },
  { title: "Melody (K-Pop)",                    file: "Melody (K-Pop).mp3",                     lang: 'en',  volIdx: 0, added: '2026-04-17' },
  { title: "Never That (B)",                    file: "Never That (B).mp3",                     lang: 'en',  volIdx: 0, added: '2026-04-16' },
  { title: "Never That (K-Pop)",                file: "Never That (K-Pop).mp3",                 lang: 'en',  volIdx: 0, added: '2026-04-17' },
  { title: "Never That (Reggae)",               file: "Never That (Reggae).mp3",                lang: 'en',  volIdx: 0, added: '2026-04-17' },
  { title: "Never That (S)",                    file: "Never That (S).mp3",                     lang: 'en',  volIdx: 0, added: '2026-04-16' },
  { title: "Not A Reward Duet (Salsa)",         file: "Not A Reward Duet (Salsa).mp3",          lang: 'en',  volIdx: 0, added: '2026-04-21' },
  { title: "Not So Bad Afterall (Salsa)",       file: "Not So Bad Afterall (Salsa).mp3",        lang: 'en',  volIdx: 0, added: '2026-04-21' },
  { title: "Glimmer (Rumba)",                   file: "Glimmer (Rumba).mp3",                    lang: 'en',  volIdx: 0, added: '2026-04-26' },
  { title: "Kislap (Rumba)",                    file: "Kislap (Rumba).mp3",                     lang: 'tl',  volIdx: 0, added: '2026-04-26' },
  { title: "Sa Lahat Ng Taon (Rave)",           file: "Sa Lahat Ng Taon (Rave).mp3",            lang: 'tl',  volIdx: 0, added: '2026-04-18' },
  { title: "Sayaw Pa Tayo (Country)",           file: "Sayaw Pa Tayo (Country).mp3",            lang: 'tl',  volIdx: 0, added: '2026-05-04' },
  { title: "Sapat Na Dahilan (Rumba)",          file: "Sapat Na Dahilan (Rumba).mp3",           lang: 'tl',  volIdx: 0, added: '2026-04-25' },
  { title: "Rumba Love (Rumba)",                file: "Rumba Love (Rumba).mp3",                 lang: 'en',  volIdx: 0, added: '2026-04-27' },
  { title: "Sa Pagitan Natin (Rumba)",          file: "Sa Pagitan Natin (Rumba).mp3",           lang: 'tl',  volIdx: 0, added: '2026-04-26' },
  { title: "Cha-Cha Love (Cha-Cha)",            file: "Cha-Cha Love (Cha-Cha).mp3",             lang: 'en',  volIdx: 0, added: '2026-04-27' },
  { title: "Sa Iyong Mga Mata (Latin Dance)",   file: "Sa Iyong Mga Mata (Latin Dance).mp3",    lang: 'tl',  volIdx: 0, added: '2026-04-23' },
  { title: "Sa Iyong Mga Mata (Synth Pop)",     file: "Sa Iyong Mga Mata (Synth Pop).mp3",      lang: 'tl',  volIdx: 0, added: '2026-04-23' },
  { title: "Sa Iyong Mga Mata (Tropical Dance)", file: "Sa Iyong Mga Mata (Tropical Dance).mp3", lang: 'tl',  volIdx: 0, added: '2026-04-23' },
  { title: "Toe to Toe (Rumba)",                file: "Toe to Toe (Rumba).mp3",                 lang: 'en',  volIdx: 0, added: '2026-04-26' },
  { title: "Together (Rumba)",                 file: "Together (Rumba).mp3",                    lang: 'en',  volIdx: 0, added: '2026-04-26' },
  { title: "Gisulat Ko Ang Bukid (Disco)",       file: "Gisulat Ko Ang Bukid (Disco).mp3",       lang: 'ceb', volIdx: 0, added: '2026-04-09' },
  { title: "Gisulat Ko Ang Bukid (Salsa)",       file: "Gisulat Ko Ang Bukid (Salsa).mp3",       lang: 'ceb', volIdx: 1, added: '2026-04-09' },
  { title: "Kasayaw Ko Habang-Buhay (Disco)",    file: "Kasayaw Ko Habang-Buhay (Disco).mp3",    lang: 'tl',  volIdx: 0 },
  { title: "Nag-Anod Ta (Cha-Cha)",              file: "Nag-Anod Ta (Cha-Cha).mp3",              lang: 'ceb', volIdx: 0, added: '2026-04-10' },
  { title: "Nag-Anod Ta (Salsa)",                file: "Nag-Anod Ta (Salsa).mp3",                lang: 'ceb', volIdx: 0, added: '2026-04-10' },
  { title: "Payong (Dance)",                     file: "Payong (Dance).mp3",                      lang: 'tl',  volIdx: 0, added: '2026-04-09' },
  { title: "Sayaw Pa Tayo (Disco)",              file: "Sayaw Pa Tayo (Disco).mp3",              lang: 'tl',  volIdx: 0 },
  { title: "Sayaw Pa Tayo (Merengue)",           file: "Sayaw Pa Tayo (Merengue).mp3",           lang: 'tl',  volIdx: 0, added: '2026-04-13' },
  { title: "Silver Moon (Bachata)",              file: "Silver Moon  (Bachata).mp3",             lang: 'en',  volIdx: 0, added: '2026-04-13' },
  { title: "Silver Moon (Cha-Cha)",              file: "Silver Moon  (Cha-Cha).mp3",             lang: 'en',  volIdx: 0, added: '2026-04-13' },
  { title: "Silver Moon (Merengue)",             file: "Silver Moon  (Merengue).mp3",            lang: 'en',  volIdx: 0, added: '2026-04-13' },
  { title: "Silver Moon (Salsa)",               file: "Silver Moon  (Salsa).mp3",               lang: 'en',  volIdx: 0, added: '2026-04-21' },
  { title: "Step By Step (Bachata)",            file: "Step By Step (Bachata).mp3",             lang: 'en',  volIdx: 0, added: '2026-04-19' },
  { title: "Step By Step (Cha-Cha)",            file: "Step By Step (Cha-Cha).mp3",             lang: 'en',  volIdx: 0, added: '2026-04-19' },
  { title: "Step By Step (Disco)",              file: "Step By Step (Disco).mp3",               lang: 'en',  volIdx: 0, added: '2026-04-19' },
  { title: "Step By Step (Merengue)",           file: "Step By Step (Merengue).mp3",            lang: 'en',  volIdx: 0, added: '2026-04-19' },
  { title: "Step By Step (Rave)",               file: "Step By Step (Rave).mp3",                lang: 'en',  volIdx: 0, added: '2026-04-19' },
  { title: "Step By Step (Reggae)",             file: "Step By Step (Reggae).mp3",              lang: 'en',  volIdx: 0, added: '2026-04-19' },
  { title: "Step By Step (Salsa)",              file: "Step By Step (Salsa).mp3",               lang: 'en',  volIdx: 0, added: '2026-04-19' },
  { title: "Step By Step (Samba)",              file: "Step By Step (Samba).mp3",               lang: 'en',  volIdx: 0, added: '2026-04-19' },
  { title: "Sumasayaw Sa Alon (Disco 2)",        file: "Sumasayaw Sa Alon (Disco 2).mp3",        lang: 'tl',  volIdx: 0 },
  { title: "Tara Na Sa Dagat (Rave)",            file: "Tara Na Sa Dagat (Rave).mp3",            lang: 'tl',  volIdx: 0, added: '2026-04-18' },
  { title: "Tara Na Sa Sagat (K-Pop)",           file: "Tara Na Sa Sagat (K-Pop).mp3",           lang: 'tl',  volIdx: 0, added: '2026-04-18' },
  { title: "Ulan O Init (EDM Dance)",            file: "Ulan O Init (EDM Dance).mp3",            lang: 'ceb', volIdx: 0, added: '2026-04-18' },
  { title: "Ulan O Init (K-Pop)",                file: "Ulan O Init (K-Pop).mp3",                lang: 'ceb', volIdx: 0, added: '2026-04-18' },
  { title: "Ulan O Init (Rave)",                 file: "Ulan O Init (Rave).mp3",                 lang: 'ceb', volIdx: 0, added: '2026-04-18' },
  { title: "We Keep Dancing (Bachata 2)",       file: "We Keep Dancing (Bachata 2).mp3",        lang: 'en',  volIdx: 0 },
  { title: "We Keep Dancing (Batchata)",        file: "We Keep Dancing (Batchata).mp3",         lang: 'en',  volIdx: 0 },
  { title: "We Keep Dancing",                   file: "We Keep Dancing (Cha-Cha).mp3",          lang: 'en',  volIdx: 0 },
  { title: "With You (EDM Dance)",               file: "With You (EDM Dance).mp3",               lang: 'en',  volIdx: 0, added: '2026-04-18' },
  { title: "With You (Rave)",                    file: "With You (Rave).mp3",                    lang: 'en',  volIdx: 0, added: '2026-04-18' },

  // ── Vol 2: Chill & Bossa ───────────────────────────────────────
  { title: "Beneath the Silver Moon",           file: "Beneath the Silver Moon.mp3",            lang: 'en',  volIdx: 0 },
  { title: "Beneath the Silver Moon (Chill)",   file: "Beneath the Silver Moon (Chill).mp3",    lang: 'en',  volIdx: 3 },
  { title: "Beneath the Silver Moon (Chill2)",  file: "Beneath the Silver Moon (Chill2).mp3",   lang: 'en',  volIdx: 4 },
  { title: "Drifting",                          file: "Drifting.mp3",                           lang: 'en',  volIdx: 0 },
  { title: "Drifting (Chill)",                  file: "Drifting (Chill).mp3",                   lang: 'en',  volIdx: 4 },
  { title: "Golden Hour Horizon",               file: "Golden Hour Horizon.mp3",                lang: 'en',  volIdx: 3 },
  { title: "Golden Hour Horizon (Bossa)",       file: "Golden Hour Horizon (Bossa).mp3",        lang: 'en',  volIdx: 4 },
  { title: "Isang Sulyap",                      file: "Isang Sulyap.mp3",                       lang: 'tl',  volIdx: 1 },
  { title: "Isang Sulyap (Bossa)",              file: "Isang Sulyap (Bossa).mp3",               lang: 'tl',  volIdx: 1 },
  { title: "Ocean",                             file: "Ocean.mp3",                  duration: "3:30", lang: 'en', volIdx: 4 },
  { title: "Ocean (Chill)",                     file: "Ocean (Chill).mp3",                      lang: 'en',  volIdx: 4 },
  { title: "Sa Lahat Ng Taon (Bossa)",          file: "Sa Lahat Ng Taon (Bossa).mp3",           lang: 'tl',  volIdx: 1 },
  { title: "Sailing",                           file: "Sailing.mp3",                            lang: 'en',  volIdx: 0 },
  { title: "Sailing (Bossa)",                   file: "Sailing (Bossa).mp3",                    lang: 'en',  volIdx: 4 },
  { title: "Same Horizon",                      file: "Same Horizon.mp3",                       lang: 'en',  volIdx: 4 },
  { title: "Same Horizon (Line)",               file: "Same Horizon Line.mp3",                  lang: 'en',  volIdx: 4 },
  { title: "Slow Time",                         file: "Slow  Time.mp3",             duration: "3:30", lang: 'en', volIdx: 3 },
  { title: "Slow Time (Chill)",                 file: "Slow Time (Chill).mp3",                  lang: 'en',  volIdx: 4 },
  { title: "Still Shining",                     file: "Still Shining.mp3",                      lang: 'en',  volIdx: 4 },
  { title: "Still Shining (Chill)",             file: "Still Shining (Chill).mp3",              lang: 'en',  volIdx: 4 },
  { title: "Warmth We Carry",                   file: "Warmth We Carry.mp3",                    lang: 'en',  volIdx: 0 },
  { title: "Warmth We Carry (Bossa)",           file: "Warmth We Carry (Bossa).mp3",            lang: 'en',  volIdx: 3 },
  { title: "Balas Ug Hangin",                   file: "Balas Ug Hangin.mp3",                    lang: 'ceb', volIdx: 1 },
  { title: "Hindi Ka Nag-Iisa",                 file: "Hindi Ka Nag-Iisa.mp3",                  lang: 'tl',  volIdx: 1 },
  { title: "Kasama Mo Ako",                     file: "Kasama Mo Ako.mp3",                      lang: 'tl',  volIdx: 1 },
  { title: "Through Every Trial",               file: "Through Every Trial.mp3",                lang: 'en',  volIdx: 4 },
  { title: "Pahulayan",                         file: "Pahulayan.mp3",              duration: "3:30", lang: 'ceb', volIdx: 1 },

  // ── Vol 3: Romantic Ballads ────────────────────────────────────
  { title: "Aking Hantungan",                   file: "Aking Hantungan.mp3",        duration: "4:10", lang: 'tl', volIdx: 2 },
  { title: "Bisan Layo Ka (Acoustic)",          file: "Bisan Layo Ka (Acoustic).mp3",           lang: 'ceb', volIdx: 2, added: '2026-04-06' },
  { title: "Daloy ng Pag-Ibig",                 file: "Daloy ng Pag-Ibig.mp3",                  lang: 'tl',  volIdx: 2 },
  { title: "Dito Ka Sa Akin",                   file: "Dito Ka Sa AKin.mp3",        duration: "3:30", lang: 'tl', volIdx: 2 },
  { title: "Hanggang sa Huli",                  file: "Hanggang sa Huli.mp3",       duration: "3:16", lang: 'tl', volIdx: 2 },
  { title: "Hanggang Sa Huli (Ballad)",         file: "Hanggang Sa Huli (Ballad).mp3",          lang: 'tl',  volIdx: 2 },
  { title: "Hanggang Sa Huli (Duet)",           file: "Hanggang Sa Huli (Duet).mp3",            lang: 'tl',  volIdx: 2 },
  { title: "Hanggang Sa Huli (R&B)",            file: "Hanggang Sa Huli (R&B).mp3",             lang: 'tl',  volIdx: 1 },
  { title: "Hanggang Sa Huli (R&B Ver2)",       file: "Hanggang Sa Huli (R&B Ver2).mp3",        lang: 'tl',  volIdx: 1 },
  { title: "Hawakan Ang Ngayon",                file: "Hawakan Ang Ngayon.mp3",     duration: "3:30", lang: 'tl', volIdx: 2 },
  { title: "Iisang Guhit",                      file: "Iisang Guhit.mp3",                       lang: 'tl',  volIdx: 2 },
  { title: "Ikaw ang Alon",                     file: "Ikaw ang Alon.mp3",          duration: "3:32", lang: 'tl', volIdx: 2 },
  { title: "Ikaw Ang Alon (Soul, R&B)",         file: "Ikaw Ang Alon (Soul, R&B).mp3",          lang: 'tl',  volIdx: 1 },
  { title: "Ikaw Ang Lahat Sa Akin",            file: "Ikaw Ang Lahat Sa Akin.mp3",             lang: 'tl',  volIdx: 2 },
  { title: "Ikaw Ang Tahanan",                  file: "Ikaw Ang Tahanan.mp3",       duration: "2:16", lang: 'tl', volIdx: 2 },
  { title: "Ikaw Ang Umaga",                    file: "Ikaw Ang Umaga.mp3",                     lang: 'tl',  volIdx: 2 },
  { title: "Ikaw Pa Rin",                       file: "Ikaw Pa Rin.mp3",            duration: "3:30", lang: 'tl', volIdx: 2 },
  { title: "Ikaw Pa Rin (Pop)",                 file: "Ikaw Pa Rin (Pop).mp3",                  lang: 'tl',  volIdx: 2 },
  { title: "Ikaw Pa Rin (Pop Ver2)",            file: "Ikaw Pa Rin (Pop Ver2).mp3",             lang: 'tl',  volIdx: 2 },
  { title: "Kislap",                            file: "Kislap.mp3",                             lang: 'tl',  volIdx: 2, added: '2026-04-26' },
  { title: "Kislap sa Dilim",                   file: "Kislap sa Dilim.mp3",                    lang: 'tl',  volIdx: 2 },
  { title: "Paruparo (Ballad)",                 file: "Paruparo (Ballad).mp3",                  lang: 'tl',  volIdx: 2, added: '2026-05-03' },
  { title: "Gisulat Ko Ang Bukid",              file: "Gisulat Ko Ang Bukid.mp3",               lang: 'ceb', volIdx: 2, added: '2026-04-09' },
  { title: "Ilalim Ng Payong 2 (R&B)",          file: "Ilalim Ng Payong 2 (R&B).mp3",           lang: 'tl',  volIdx: 2, added: '2026-04-19' },
  { title: "Ilalom Sa Payong",                  file: "Ilalom Sa Payong.mp3",                   lang: 'ceb', volIdx: 1, added: '2026-04-09' },
  { title: "Sa Iyong Mga Mata 2 (Ballad)",      file: "Sa Iyong Mga Mata 2 (Ballad).mp3",       lang: 'tl',  volIdx: 2, added: '2026-04-23' },
  { title: "Sa Iyong Mga Mata (Ballad)",        file: "Sa Iyong Mga Mata (Ballad).mp3",         lang: 'tl',  volIdx: 2, added: '2026-04-23' },
  { title: "Sa Iyong Mga Mata (Duet)",          file: "Sa Iyong Mga Mata (Duet).mp3",           lang: 'tl',  volIdx: 2, added: '2026-04-23' },
  { title: "Sa Iyong Mga Mata (Latin Pop)",     file: "Sa Iyong Mga Mata (Latin Pop).mp3",      lang: 'tl',  volIdx: 2, added: '2026-04-23' },
  { title: "Sa Iyong Mga Mata (Pop Ballad)",    file: "Sa Iyong Mga Mata (Pop Ballad).mp3",     lang: 'tl',  volIdx: 2, added: '2026-04-23' },
  { title: "Sa Hirap at Ginhawa (Pop)",         file: "Sa Hirap at Ginhawa  (Pop).mp3",         lang: 'tl',  volIdx: 2, added: '2026-04-19' },
  { title: "Ulan O Init",                       file: "Ulan O Init.mp3",                        lang: 'ceb', volIdx: 2, added: '2026-04-10' },
  { title: "Himig Ng Ating Kahapon",            file: "Himig Ng Ating Kahapon (Pop).mp3",       lang: 'tl',  volIdx: 2 },
  { title: "Himig Ng Ating Kahapon (Pop Ver2)", file: "Himig Ng Ating Kahapon (Pop Ver2).mp3",  lang: 'tl',  volIdx: 2 },
  { title: "Sapat Na Dahilan (Tango)",          file: "Sapat Na Dahilan (Tango).mp3",           lang: 'tl',  volIdx: 0, added: '2026-04-25' },
  { title: "Tahanan",                           file: "Tahanan.mp3",                            lang: 'tl',  volIdx: 2 },
  { title: "Tahanan (Ver 2)",                   file: "Tahanan (Ver 2).mp3",                    lang: 'tl',  volIdx: 2 },
  { title: "Tahanan (R&B Funky)",               file: "Tahanan (R&B Funky).mp3",                lang: 'tl',  volIdx: 1 },
  { title: "Tahanan (R&B Funky Ver2)",          file: "Tahanan (R&B Funky Ver2).mp3",           lang: 'tl',  volIdx: 1 },
  { title: "My Joy 2 (Disco-Pop)",              file: "My Joy 2 (Disco-Pop).mp3",               lang: 'en',  volIdx: 0, added: '2026-07-08' },
  { title: "My Joy 2 (Nu-Disco)",               file: "My Joy 2 (Nu-Disco).mp3",                lang: 'en',  volIdx: 0, added: '2026-07-08' },
  { title: "Ikaw Ang Kalipay (Nu-Disco)",       file: "Ikaw Ang Kalipay (Nu-Disco).mp3",        lang: 'ceb', volIdx: 0, added: '2026-07-09' },
  { title: "Ikaw Ang Kalipay 2 (Nu-Disco)",     file: "Ikaw Ang Kalipay 2 (Nu-Disco).mp3",      lang: 'ceb', volIdx: 0, added: '2026-07-09' },
  { title: "Ikaw Ang Ligaya (Nu-Disco)",        file: "Ikaw Ang Ligaya (Nu-Disco).mp3",         lang: 'tl',  volIdx: 0, added: '2026-07-09' },
  { title: "Ikaw Ang Ligaya (Upbeat)",          file: "Ikaw Ang Ligaya (Upbeat).mp3",           lang: 'tl',  volIdx: 0, added: '2026-07-09' },
  { title: "Ikaw Ang Ligaya 2 (Nu-Disco)",      file: "Ikaw Ang Ligaya 2 (Nu-Disco).mp3",       lang: 'tl',  volIdx: 0, added: '2026-07-09' },
  { title: "Labaw Pa (Disco-Pop)",              file: "Labaw Pa (Disco-Pop).mp3",               lang: 'ceb', volIdx: 0, added: '2026-07-09' },
  { title: "Mag-Uban Ko Nimo (Nu-Disco)",       file: "Mag-Uban Ko Nimo (Nu-Disco).mp3",        lang: 'ceb', volIdx: 0, added: '2026-07-10' },
  { title: "You Are The Word (Disco-Pop)",      file: "You Are The Word (Disco-Pop).mp3",       lang: 'en',  volIdx: 0, added: '2026-07-10' },

  // ── Vol 4: Heart & Soul ────────────────────────────────────────
  { title: "Ania Ako",                          file: "Ania Ako.mp3",                           lang: 'ceb', volIdx: 1 },
  { title: "Ania Ako (R&B)",                    file: "Ania Ako (R&B).mp3",                     lang: 'ceb', volIdx: 1 },
  { title: "Ania Ako (Soul)",                   file: "Ania Ako (Soul).mp3",                    lang: 'ceb', volIdx: 1 },
  { title: "Bisan Layo Ka (R&B)",               file: "Bisan Layo Ka (R&B).mp3",                lang: 'ceb', volIdx: 1, added: '2026-04-06' },
  { title: "Dagat at Baybayin",                 file: "Dagat at Baybayin.mp3",                  lang: 'tl',  volIdx: 1 },
  { title: "Dagat at Baybayin (Male)",          file: "Dagat at Baybayin (Male).mp3",           lang: 'tl',  volIdx: 1 },
  { title: "Di Madaling Mahalin (2)",           file: "Di Madaling Mahalin (2).mp3",            lang: 'tl',  volIdx: 1, added: '2026-04-14' },
  { title: "Hindi Ka Dead Star",                file: "Hindi Ka Dead Star.mp3",     duration: "3:30", lang: 'tl', volIdx: 1 },
  { title: "Ibang Daan",                        file: "Ibang Daan.mp3",             duration: "3:39", lang: 'tl', volIdx: 1 },
  { title: "Isang Linggo Lang",                 file: "Isang Linggo Lang.mp3",      duration: "3:58", lang: 'tl', volIdx: 1 },
  { title: "Isang Linggo Lang (Pop)",           file: "Isang Linggo (Pop).mp3",                 lang: 'tl',  volIdx: 1 },
  { title: "Isang Linggo Lang (Pop Ver2)",      file: "Isang Linggo (Pop Ver2).mp3",            lang: 'tl',  volIdx: 1 },
  { title: "Hanggang Kailan",                   file: "Hanggang Kailan.mp3",                    lang: 'tl',  volIdx: 1, added: '2026-04-06' },
  { title: "Gisulat Ko Ang Bukid (Duet)",       file: "Gisulat Ko Ang Bukid (Duet).mp3",        lang: 'ceb', volIdx: 1, added: '2026-04-09' },
  { title: "I Wrote The Mountains (Jazz)",      file: "I Wrote The Mountains (Jazz).mp3",       lang: 'en',  volIdx: 1, added: '2026-04-08' },
  { title: "Ilalim Ng Payong (Indie Pop)",      file: "Ilalim Ng Payong (Indie Pop).mp3",       lang: 'tl',  volIdx: 1, added: '2026-04-09' },
  { title: "Paruparo Sa Balikat (Acoustic)",    file: "Paruparo Sa Balikat (Acoustic).mp3",     lang: 'tl',  volIdx: 1, added: '2026-05-03' },
  { title: "Ilalim ng Payong (R&B)",            file: "Ilalim ng Payong (R&B).mp3",             lang: 'tl',  volIdx: 1, added: '2026-04-09' },
  { title: "Ilalom Sa Payong (R&B)",            file: "Ilalom Sa Payong (R&B).mp3",             lang: 'ceb', volIdx: 1, added: '2026-04-09' },
  { title: "Kahit Saan Pa Mapunta",             file: "Kahit Saan Pa Mapunta.mp3",              lang: 'tl',  volIdx: 1 },
  { title: "Kahit Ulan O Araw",                 file: "Kahit Ulan O Araw.mp3",                  lang: 'tl',  volIdx: 1 },
  { title: "Kay Layo Mo Man",                   file: "Kay Layo Mo Man.mp3",                    lang: 'tl',  volIdx: 1, added: '2026-04-06' },
  { title: "Liyab sa Dilim",                    file: "Liyab sa Dilim.mp3",                     lang: 'tl',  volIdx: 1 },
  { title: "Magkasama",                         file: "Magkasama.mp3",                          lang: 'tl',  volIdx: 1 },
  { title: "Magkasama (R&B-Pop)",               file: "Magkasama (R&B-Pop).mp3",                lang: 'tl',  volIdx: 1 },
  { title: "Magkasama (Tayo Lagi)",             file: "Magkasama Tayo Lagi.mp3",                lang: 'tl',  volIdx: 1 },
  { title: "Mahalaga Nandito Ka",               file: "Mahalaga Nandito Ka.mp3",    duration: "3:55", lang: 'tl', volIdx: 1 },
  { title: "Morning Rain",                      file: "Morning Rain.mp3",                       lang: 'en',  volIdx: 1, added: '2026-04-04' },
  { title: "Muli",                              file: "Muli.mp3",                   duration: "3:30", lang: 'tl', volIdx: 0 },
  { title: "Nagbabalik",                        file: "Nagbabalik.mp3",                         lang: 'tl',  volIdx: 1 },
  { title: "Sa Iyong Mga Mata (Jazz)",          file: "Sa Iyong Mga Mata (Jazz).mp3",           lang: 'tl',  volIdx: 1, added: '2026-04-23' },
  { title: "Sa Iyong Mga Mata (R&B)",           file: "Sa Iyong Mga Mata (R&B).mp3",            lang: 'tl',  volIdx: 1, added: '2026-04-23' },
  { title: "Ulan O Init (Bossa)",               file: "Ulan O Init (Bossa).mp3",                lang: 'ceb', volIdx: 1, added: '2026-04-10' },
  { title: "Ulan O Init (2)",                   file: "Ulan O Init (2).mp3",                    lang: 'ceb', volIdx: 1, added: '2026-04-10' },
  { title: "Payong (Duet)",                     file: "Payong (Duet).mp3",                      lang: 'tl',  volIdx: 1, added: '2026-04-09' },
  { title: "Himig Ng Ating Kahapon (R&B Funky)", file: "Himig Ng Ating Kahapon (R&B Funky).mp3", lang: 'tl',  volIdx: 1 },
  { title: "Ang Bituin",                        file: "Ang Bituin.mp3",                         lang: 'tl',  volIdx: 1, added: '2026-07-06' },
  { title: "Ang Bituin (2)",                    file: "Ang Bituin 2.mp3",                       lang: 'tl',  volIdx: 1, added: '2026-07-06' },
  { title: "Ang Bituin (Duet)",                 file: "Ang Bituin Duet.mp3",                    lang: 'tl',  volIdx: 1, added: '2026-07-06' },
  { title: "Unang Tingin",                      file: "Unang Tingin.mp3",                       lang: 'tl',  volIdx: 1, added: '2026-07-06' },
  { title: "Unang Tingin (2)",                  file: "Unang Tingin 2.mp3",                     lang: 'tl',  volIdx: 1, added: '2026-07-06' },
  { title: "Higit Pa (2)",                      file: "Higit Pa 2.mp3",                         lang: 'tl',  volIdx: 1, added: '2026-07-07' },
  { title: "Higit Pa (2) (Ballad)",              file: "Higit Pa 2 (Ballad).mp3",                lang: 'tl',  volIdx: 1, added: '2026-07-07' },
  { title: "Ang Bituin (Bossa)",                 file: "Ang Bituin (Bossa).mp3",                 lang: 'tl',  volIdx: 1, added: '2026-07-09' },
  { title: "Higit Pa (Bossa)",                   file: "Higit Pa (Bossa).mp3",                   lang: 'tl',  volIdx: 1, added: '2026-07-09' },
  { title: "Ikaw Ang Kalipay (Bossa)",           file: "Ikaw Ang Kalipay (Bossa).mp3",           lang: 'ceb', volIdx: 1, added: '2026-07-09' },
  { title: "Ikaw Ang Ligaya (Bossa)",            file: "Ikaw Ang Ligaya (Bossa).mp3",            lang: 'tl',  volIdx: 1, added: '2026-07-09' },
  { title: "Ikaw Ang Ligaya 2 (Acoustic)",       file: "Ikaw Ang Ligaya 2 (Acoustic).mp3",       lang: 'tl',  volIdx: 1, added: '2026-07-09' },
  { title: "Labaw Pa (Bossa)",                   file: "Labaw Pa (Bossa).mp3",                   lang: 'ceb', volIdx: 1, added: '2026-07-09' },
  { title: "Ikaw Ang Pulong (Acoustic)",         file: "Ikaw Ang Pulong (Acoustic).mp3",         lang: 'ceb', volIdx: 1, added: '2026-07-10' },
  { title: "Mag-Uban Ko Nimo (Bossa)",           file: "Mag-Uban Ko Nimo (Bossa).mp3",           lang: 'ceb', volIdx: 1, added: '2026-07-10' },
  { title: "Mag-Uban Ko Nimo 2 (Nu-Disco)",      file: "Mag-Uban Ko Nimo 2 (Nu-Disco).mp3",      lang: 'ceb', volIdx: 1, added: '2026-07-10' },
  { title: "Hanggang Kailan (Duet)",             file: "Hanggang Kailan (Duet).mp3",             lang: 'tl',  volIdx: 1, added: '2026-07-12' },
  { title: "Hangtod Kanus-a",                    file: "Hangtod Kanus-a.mp3",                    lang: 'ceb', volIdx: 1, added: '2026-07-12' },
  { title: "Hangtod Kanus-a (Bossa)",            file: "Hangtod Kanus-a (Bossa).mp3",            lang: 'ceb', volIdx: 1, added: '2026-07-12' },
  { title: "Sama Sa Bulak (Female)",             file: "Sama Sa Bulak (Female).mp3",             lang: 'ceb', volIdx: 1, added: '2026-07-12' },

  // ── Vol 5: Devotion ────────────────────────────────────────────
  { title: "Dito Ka Sa Akin (Synth-Pop)",        file: "Dito Ka Sa AKin (Synth-Pop).mp3",        lang: 'tl',  volIdx: 2 },
  { title: "Dito Ka Sa Akin (Synth-Pop2)",       file: "Dito Ka Sa AKin (Synth-Pop2).mp3",       lang: 'tl',  volIdx: 2 },
  { title: "Di Madaling Mahalin",                file: "Di Madaling Mahalin.mp3",                lang: 'tl',  volIdx: 2, added: '2026-04-14' },
  { title: "Habang Tumatagal",                   file: "Habang Tumatagal.mp3",       duration: "3:30", lang: 'tl', volIdx: 2 },
  { title: "Habang Tumatagal (R&B)",             file: "Habang Tumatagal (R&B).mp3",             lang: 'tl',  volIdx: 2 },
  { title: "Hawakan Ang Ngayon (Synth-Pop)",     file: "Hawakan Ang Ngayon (Synth-Pop).mp3",     lang: 'tl',  volIdx: 2 },
  { title: "Hawakan Ang Ngayon (Synth-Pop2)",    file: "Hawakan Ang Ngayon (Synth-Pop2).mp3",    lang: 'tl',  volIdx: 2 },
  { title: "Ito Tayo",                          file: "Ito Tayo.mp3",                           lang: 'tl',  volIdx: 2 },
  { title: "Kanlungan",                         file: "Kanlungan.mp3",              duration: "3:30", lang: 'tl', volIdx: 2 },
  { title: "Kung Nandito Ka Sana",              file: "Kung Nandito Ka Sana.mp3",   duration: "3:30", lang: 'tl', volIdx: 2 },
  { title: "Muling Humihinga",                  file: "Muling Humihinga.mp3",                   lang: 'tl',  volIdx: 2 },
  { title: "Nanatiling Bakas",                  file: "Nanatiling Bakas.mp3",       duration: "3:43", lang: 'tl', volIdx: 2 },
  { title: "Nandito Ako",                       file: "Nandito Ako.mp3",                        lang: 'tl',  volIdx: 2 },
  { title: "Nandito Ako (Nu-Jazz)",             file: "Nandito Ako (Nu-Jazz).mp3",              lang: 'tl',  volIdx: 2 },
  { title: "Payong (Acoustic)",                 file: "Payong (Acoustic).mp3",                  lang: 'tl',  volIdx: 2, added: '2026-04-09' },
  { title: "Payong (Ballad)",                   file: "Payong (Ballad).mp3",                    lang: 'tl',  volIdx: 2, added: '2026-04-09' },
  { title: "Payong (Duet 2)",                   file: "Payong (Duet 2).mp3",                    lang: 'tl',  volIdx: 2, added: '2026-04-09' },
  { title: "Payong (Solo)",                     file: "Payong (Solo).mp3",                      lang: 'tl',  volIdx: 2, added: '2026-04-09' },
  { title: "Sa Dilim, Ikaw at Ako",             file: "Sa Dilim, Ikaw at Ako.mp3",  duration: "3:30", lang: 'tl', volIdx: 2 },
  { title: "Sa Ilalim ng Payong",               file: "Sa Ilalim ng Payong.mp3",    duration: "3:30", lang: 'tl', volIdx: 2 },
  { title: "Sa Maulang Biyahe",                 file: "Sa Maulang Biyahe.mp3",                  lang: 'tl',  volIdx: 2 },
  { title: "Sa Lahat Ng Taon",                  file: "Sa Lahat Ng Taon.mp3",                   lang: 'tl',  volIdx: 2 },
  { title: "Sa Tabing Dagat",                   file: "Sa Tabing Dagat.mp3",        duration: "3:30", lang: 'tl', volIdx: 2 },
  { title: "Sa Yakap Mo",                       file: "Sa Yakap Mo.mp3",            duration: "3:30", lang: 'tl', volIdx: 2 },
  { title: "Sapat Na",                          file: "Sapat Na.mp3",                           lang: 'tl',  volIdx: 2 },
  { title: "Tadhana",                           file: "Tadhana.mp3",                duration: "3:30", lang: 'tl', volIdx: 2 },
  { title: "Tadhana (Male)",                    file: "Tadhana (Male).mp3",                     lang: 'tl',  volIdx: 2 },
  { title: "Tanging Yaman",                     file: "Tanging Yaman.mp3",          duration: "3:30", lang: 'tl', volIdx: 2 },
  { title: "Higit Pa",                          file: "Higit Pa.mp3",                           lang: 'tl',  volIdx: 2, added: '2026-07-07' },
  { title: "Higit Pa (Ballad)",                 file: "Higit Pa (Ballad).mp3",                  lang: 'tl',  volIdx: 2, added: '2026-07-07' },
  { title: "Ang Bituin 2 (Bossa)",               file: "Ang Bituin 2 (Bossa).mp3",               lang: 'tl',  volIdx: 2, added: '2026-07-09' },
  { title: "Higit Pa 2 (Bossa)",                 file: "Higit Pa 2 (Bossa).mp3",                 lang: 'tl',  volIdx: 2, added: '2026-07-09' },
  { title: "Ikaw Ang Kalipay (Acoustic)",        file: "Ikaw Ang Kalipay (Acoustic).mp3",        lang: 'ceb', volIdx: 2, added: '2026-07-09' },
  { title: "Ikaw Ang Kalipay 2 (Bossa)",         file: "Ikaw Ang Kalipay 2 (Bossa).mp3",         lang: 'ceb', volIdx: 2, added: '2026-07-09' },
  { title: "Ikaw Ang Ligaya (Acoustic)",         file: "Ikaw Ang Ligaya (Acoustic).mp3",         lang: 'tl',  volIdx: 2, added: '2026-07-09' },
  { title: "Ikaw Ang Ligaya 2 (Bossa)",          file: "Ikaw Ang Ligaya 2 (Bossa).mp3",          lang: 'tl',  volIdx: 2, added: '2026-07-09' },
  { title: "Ang Bituin (Acoustic)",              file: "Ang Bituin (Acoustic).mp3",              lang: 'tl',  volIdx: 2, added: '2026-07-10' },
  { title: "Labaw Pa (Acoustic)",                file: "Labaw Pa (Acoustic).mp3",                lang: 'ceb', volIdx: 2, added: '2026-07-10' },
  { title: "Mag-Uban Ko Nimo 2 (Bossa)",         file: "Mag-Uban Ko Nimo 2 (Bossa).mp3",         lang: 'ceb', volIdx: 2, added: '2026-07-10' },
  { title: "Hanggang Kailan (Neoclassical)",     file: "Hanggang Kailan (Neoclassical).mp3",     lang: 'tl',  volIdx: 2, added: '2026-07-12' },
  { title: "Hangtod Kanus-a (Pop)",              file: "Hangtod Kanus-a (Pop).mp3",              lang: 'ceb', volIdx: 2, added: '2026-07-12' },
  { title: "Sama Sa Bulak (Male)",               file: "Sama Sa Bulak (Male).mp3",               lang: 'ceb', volIdx: 2, added: '2026-07-12' },

  // ── Vol 6: English Love ────────────────────────────────────────
  { title: "Always",                            file: "Always.mp3",                             lang: 'en',  volIdx: 3 },
  { title: "Already Enough (Ballad)",           file: "Already Enough (Ballad).mp3",            lang: 'en',  volIdx: 3, added: '2026-04-13' },
  { title: "Always (UK House)",                 file: "Always (UK House).mp3",                  lang: 'en',  volIdx: 4 },
  { title: "Always You",                        file: "Always You.mp3",                         lang: 'en',  volIdx: 3 },
  { title: "As Time Goes On (UK House)",        file: "As Time Goes On (UK House).mp3",         lang: 'en',  volIdx: 0 },
  { title: "Before I Healed (Acoustic)",        file: "Before I Healed (Acoustic).mp3",         lang: 'en',  volIdx: 3, added: '2026-04-17' },
  { title: "Before The Light (Ballad)",         file: "Before The Light (Ballad).mp3",          lang: 'en',  volIdx: 3, added: '2026-04-17' },
  { title: "Before Its Gone",                   file: "Before Its Gone.mp3",                    lang: 'en',  volIdx: 3, added: '2026-04-16' },
  { title: "Because of You",                    file: "Because of You.mp3",                     lang: 'en',  volIdx: 3 },
  { title: "Between Us",                        file: "Between Us.mp3",                         lang: 'en',  volIdx: 0 },
  { title: "Coming Back to You",                file: "Coming Back to You.mp3",                 lang: 'en',  volIdx: 3 },
  { title: "Dead Star (Acoustic)",              file: "Dead Star (Acoustic).mp3",               lang: 'en',  volIdx: 3, added: '2026-04-17' },
  { title: "Drifting (R&B)",                    file: "Drifting (R&B).mp3",                     lang: 'en',  volIdx: 3, added: '2026-04-17' },
  { title: "Every Season (Pop-Soul)",           file: "Every Season (Pop-Soul).mp3",            lang: 'en',  volIdx: 0 },
  { title: "Faithful Hearts 2 R&B",             file: "Faithful Hearts 2 R&B.mp3",              lang: 'en',  volIdx: 3, added: '2026-04-20' },
  { title: "Faithful Hearts Ballad",            file: "Faithful Hearts Ballad.mp3",             lang: 'en',  volIdx: 3, added: '2026-04-20' },
  { title: "Faithful Hearts (OPM)",             file: "Faithful Hearts (OPM).mp3",              lang: 'en',  volIdx: 3, added: '2026-04-20' },
  { title: "Flames (Acoustic)",                 file: "Flames (Acoustic).mp3",                  lang: 'en',  volIdx: 3, added: '2026-04-17' },
  { title: "Flames 2 (Acoustic)",               file: "Flames 2 (Acoustic).mp3",                lang: 'en',  volIdx: 3, added: '2026-04-17' },
  { title: "Forever You",                       file: "Forever You.mp3",                        lang: 'en',  volIdx: 3 },
  { title: "Home (Jazz)",                       file: "Home (Jazz).mp3",                        lang: 'en',  volIdx: 3, added: '2026-04-17' },
  { title: "Home 2 (Jazz)",                     file: "Home 2 (Jazz).mp3",                      lang: 'en',  volIdx: 3, added: '2026-04-17' },
  { title: "I Am Yours",                        file: "I Am Yours.mp3",                         lang: 'en',  volIdx: 3 },
  { title: "I Found You Again",                 file: "I Found You Again.mp3",                  lang: 'en',  volIdx: 3 },
  { title: "I Love You More",                   file: "I Love You More.mp3",                    lang: 'en',  volIdx: 0 },
  { title: "In Your Eyes (Ballad)",             file: "In Your Eyes (Ballad).mp3",              lang: 'en',  volIdx: 3, added: '2026-04-23' },
  { title: "I Wrote The Mountains (Acoustic)",  file: "I Wrote The Mountains (Acoustic).mp3",   lang: 'en',  volIdx: 3, added: '2026-04-08' },
  { title: "I'll Hold The Line",                file: "I'll Hold The Line.mp3",     duration: "3:30", lang: 'en', volIdx: 0 },
  { title: "I'm Gonna Love You",                file: "I'm Gonna Love You.mp3",                 lang: 'en',  volIdx: 3 },
  { title: "In Your Embrace",                   file: "In Your Embrace.mp3",                    lang: 'en',  volIdx: 3 },
  { title: "Intertwined",                       file: "Intertwined.mp3",                        lang: 'en',  volIdx: 3 },
  { title: "It's You",                          file: "It's You.mp3",               duration: "3:30", lang: 'en', volIdx: 0 },
  { title: "Just Because",                      file: "Just Because.mp3",                       lang: 'en',  volIdx: 3, added: '2026-04-14' },
  { title: "Gentle Goodbye",                    file: "Gentle Goodbye.mp3",                     lang: 'en',  volIdx: 3, added: '2026-05-03' },
  { title: "Just Stay With Me",                 file: "Just Stay With Me.mp3",                  lang: 'en',  volIdx: 0 },
  { title: "Lost In The Beat (Acoustic)",       file: "Lost In The Beat (Acoustic).mp3",        lang: 'en',  volIdx: 3, added: '2026-04-17' },
  { title: "Maybe Happy Ending (Ballad)",       file: "Maybe Happy Ending (Ballad).mp3",        lang: 'en',  volIdx: 3, added: '2026-04-17' },
  { title: "My Once In A Lifetime",             file: "My Once In A Lifetime.mp3",              lang: 'en',  volIdx: 3, added: '2026-05-03' },
  { title: "My Safe Place (Chill)",             file: "My Safe Place (Chill).mp3",              lang: 'en',  volIdx: 3, added: '2026-04-04' },
  { title: "Never That",                        file: "Never That.mp3",                         lang: 'en',  volIdx: 3, added: '2026-04-16' },
  { title: "Now Intertwined",                   file: "Now Intertwined.mp3",                    lang: 'en',  volIdx: 3 },
  { title: "Together, Always",                  file: "Together, Always.mp3",                   lang: 'en',  volIdx: 0 },
  { title: "Still Building",                    file: "Still Building.mp3",                     lang: 'en',  volIdx: 3, added: '2026-07-07' },
  { title: "Still Building (2)",                file: "Still Building 2.mp3",                   lang: 'en',  volIdx: 3, added: '2026-07-07' },
  { title: "Still Building (2) (Synth-Pop)",    file: "Still Building 2 (Synth-Pop).mp3",       lang: 'en',  volIdx: 3, added: '2026-07-07' },
  { title: "My Joy",                            file: "My Joy.mp3",                             lang: 'en',  volIdx: 3, added: '2026-07-08' },
  { title: "My Joy (Bossa)",                    file: "My Joy (Bossa).mp3",                     lang: 'en',  volIdx: 3, added: '2026-07-08' },
  { title: "My Joy (Disco-Pop)",                file: "My Joy (Disco-Pop).mp3",                 lang: 'en',  volIdx: 3, added: '2026-07-08' },
  { title: "My Joy (Nu-Disco)",                 file: "My Joy (Nu-Disco).mp3",                  lang: 'en',  volIdx: 3, added: '2026-07-08' },
  { title: "My Joy 2 (Bossa)",                  file: "My Joy 2 (Bossa).mp3",                   lang: 'en',  volIdx: 3, added: '2026-07-08' },
  { title: "My Joy 2 (Female)",                 file: "My Joy 2 (Female).mp3",                  lang: 'en',  volIdx: 3, added: '2026-07-08' },
  { title: "Still Building (Bossa)",            file: "Still Building (Bossa).mp3",             lang: 'en',  volIdx: 3, added: '2026-07-09' },
  { title: "You Are The Word (Bossa)",          file: "You Are The Word (Bossa).mp3",           lang: 'en',  volIdx: 3, added: '2026-07-10' },
  { title: "You Are The Word 2 (Disco-Pop)",    file: "You Are The Word 2 (Disco-Pop).mp3",     lang: 'en',  volIdx: 3, added: '2026-07-10' },
  { title: "You Are The Word 3 (Bossa)",        file: "You Are The Word 3 (Bossa).mp3",         lang: 'en',  volIdx: 3, added: '2026-07-10' },
  { title: "Every Season (Acoustic Pop)",       file: "Every Season (Acoustic Pop).mp3",        lang: 'en',  volIdx: 3, added: '2026-07-11' },
  { title: "Every Season (Duet)",               file: "Every Season (Duet).mp3",                lang: 'en',  volIdx: 3, added: '2026-07-11' },
  { title: "Every Season (Neoclassical)",       file: "Every Season (Neoclassical).mp3",        lang: 'en',  volIdx: 3, added: '2026-07-11' },
  { title: "Every Season (Piano Ballad)",       file: "Every Season (Piano Ballad).mp3",        lang: 'en',  volIdx: 3, added: '2026-07-11' },
  { title: "Every Season (Pop Ballad)",         file: "Every Season (Pop Ballad).mp3",          lang: 'en',  volIdx: 3, added: '2026-07-11' },
  { title: "Like A Rose",                       file: "Like A Rose.mp3",                        lang: 'en',  volIdx: 3, added: '2026-07-12' },
  { title: "Like A Rose (Synth-Pop)",           file: "Like A Rose (Synth-Pop).mp3",            lang: 'en',  volIdx: 3, added: '2026-07-12' },

  // ── Vol 7: English Soul ────────────────────────────────────────
  { title: "As Time Goes On",                   file: "As Time Goes On.mp3",                    lang: 'en',  volIdx: 3 },
  { title: "Already Enough",                    file: "Already Enough.mp3",                     lang: 'en',  volIdx: 4, added: '2026-04-13' },
  { title: "Gentle Goodbye (Jazz)",             file: "Gentle Goodbye (Jazz).mp3",              lang: 'en',  volIdx: 4, added: '2026-05-03' },
  { title: "Before It's Gone Duet (Jazz)",      file: "Before It's Gone Duet (Jazz).mp3",       lang: 'en',  volIdx: 4, added: '2026-04-20' },
  { title: "Before Its Gone (Chill)",           file: "Before Its Gone (Chill).mp3",            lang: 'en',  volIdx: 4, added: '2026-04-16' },
  { title: "Before I Healed Duet (Jazz)",       file: "Before I Healed Duet (Jazz).mp3",        lang: 'en',  volIdx: 4, added: '2026-04-20' },
  { title: "Before I Healed",                   file: "Before I Healed.mp3",                    lang: 'en',  volIdx: 4, added: '2026-04-05' },
  { title: "Before The Light Duet (Jazz)",      file: "Before The Light Duet (Jazz).mp3",       lang: 'en',  volIdx: 4, added: '2026-04-20' },
  { title: "Before The Light",                  file: "Before The Light.mp3",                   lang: 'en',  volIdx: 4, added: '2026-04-05' },
  { title: "Dancing Duet (Jazz)",               file: "Dancing Duet (Jazz).mp3",                lang: 'en',  volIdx: 4, added: '2026-04-20' },
  { title: "Dead Star",                         file: "Dead Star.mp3",                          lang: 'en',  volIdx: 4 },
  { title: "Faithful Hearts (Bossa)",           file: "Faithful Hearts (Bossa).mp3",            lang: 'en',  volIdx: 4, added: '2026-04-20' },
  { title: "Faithful Hearts Duet (Jazz)",       file: "Faithful Hearts Duet (Jazz).mp3",        lang: 'en',  volIdx: 4, added: '2026-04-20' },
  { title: "Faithful Hearts R&B",               file: "Faithful Hearts R&B.mp3",                lang: 'en',  volIdx: 4, added: '2026-04-20' },
  { title: "Flames Duet (Jazz)",                file: "Flames Duet (Jazz).mp3",                 lang: 'en',  volIdx: 4, added: '2026-04-20' },
  { title: "Flames",                            file: "Flames.mp3",                             lang: 'en',  volIdx: 4 },
  { title: "Flames (in the Dark Room)",         file: "Flames in the Dark Room.mp3",            lang: 'en',  volIdx: 4 },
  { title: "Home",                              file: "Home.mp3",                               lang: 'en',  volIdx: 4 },
  { title: "I Wrote The Mountains",             file: "I Wrote The Mountains.mp3",              lang: 'en',  volIdx: 4, added: '2026-04-08' },
  { title: "In Your Eyes Duet (Jazz)",          file: "In Your Eyes Duet (Jazz).mp3",           lang: 'en',  volIdx: 4, added: '2026-04-23' },
  { title: "Just Because Duet (Jazz)",          file: "Just Because Duet (Jazz).mp3",           lang: 'en',  volIdx: 4, added: '2026-04-20' },
  { title: "Just Because (Soft Jazz)",          file: "Just Because (Soft Jazz).mp3",           lang: 'en',  volIdx: 4, added: '2026-04-14' },
  { title: "Lost In The Beat Duet (Jazz)",      file: "Lost In The Beat Duet (Jazz).mp3",       lang: 'en',  volIdx: 4, added: '2026-04-20' },
  { title: "Maybe Happy Ending",                file: "Maybe Happy Ending.mp3",                 lang: 'en',  volIdx: 4 },
  { title: "Melody Duet (Jazz)",                file: "Melody Duet (Jazz).mp3",                 lang: 'en',  volIdx: 4, added: '2026-04-20' },
  { title: "My Melody",                         file: "My Melody.mp3",                          lang: 'en',  volIdx: 4, added: '2026-04-16' },
  { title: "My Safe Place",                     file: "My Safe Place.mp3",                      lang: 'en',  volIdx: 0 },
  { title: "My Song (K-Pop)",                   file: "My Song (K-Pop).mp3",                    lang: 'en',  volIdx: 0, added: '2026-04-17' },
  { title: "My Song Duet (Jazz)",               file: "My Song Duet (Jazz).mp3",                lang: 'en',  volIdx: 4, added: '2026-04-20' },
  { title: "My Song",                           file: "My Song.mp3",                            lang: 'en',  volIdx: 4, added: '2026-04-16' },
  { title: "Never That Duet (Jazz)",            file: "Never That Duet (Jazz).mp3",             lang: 'en',  volIdx: 4, added: '2026-04-20' },
  { title: "Never That (Soul)",                 file: "Never That (Soul).mp3",                  lang: 'en',  volIdx: 4, added: '2026-04-16' },
  { title: "Not A Reward Duet (Jazz)",          file: "Not A Reward Duet (Jazz).mp3",           lang: 'en',  volIdx: 4, added: '2026-04-20' },
  { title: "Not A Reward",                      file: "Not A Reward.mp3",                       lang: 'en',  volIdx: 4, added: '2026-04-05' },
  { title: "Not So Bad Afterall",               file: "Not So Bad Afterall.mp3",                lang: 'en',  volIdx: 4 },
  { title: "Not So Bad Afterall (Indie)",       file: "Not So Bad Afterall (Indie).mp3",        lang: 'en',  volIdx: 4 },
  { title: "Old and Gray",                      file: "Old and Gray.mp3",                       lang: 'en',  volIdx: 4 },
  { title: "Sanctuary",                         file: "Sanctuary.mp3",              duration: "3:30", lang: 'en', volIdx: 4 },
  { title: "Steady Hearts Duet (Jazz)",         file: "Steady Hearts Duet (Jazz).mp3",          lang: 'en',  volIdx: 4, added: '2026-04-20' },
  { title: "Steady Hearts (Chill)",             file: "Steady Hearts (Chill).mp3",              lang: 'en',  volIdx: 4, added: '2026-04-04' },
  { title: "Step By Step Duet (Jazz)",          file: "Step By Step Duet (Jazz).mp3",           lang: 'en',  volIdx: 4, added: '2026-04-20' },
  { title: "The Echo",                          file: "The Echo.mp3",                           lang: 'en',  volIdx: 4 },
  { title: "The Medicine of Us",                file: "The Medicine of Us.mp3",                 lang: 'en',  volIdx: 4, added: '2026-04-05' },
  { title: "The Rhythm of the Dark",            file: "The Rhythm of the Dark.mp3", duration: "3:30", lang: 'en', volIdx: 4 },
  { title: "The World You Chose",               file: "The World You Chose.mp3",    duration: "3:30", lang: 'en', volIdx: 4 },
  { title: "Thankful Duet (Jazz)",              file: "Thankful Duet (Jazz).mp3",               lang: 'en',  volIdx: 4, added: '2026-04-20' },
  { title: "This Is Us",                        file: "This Is Us.mp3",                         lang: 'en',  volIdx: 4 },
  { title: "With You (2)",                      file: "With You (2).mp3",                       lang: 'en',  volIdx: 4, added: '2026-04-10' },
  { title: "With You Duet (Jazz)",              file: "With You Duet (Jazz).mp3",               lang: 'en',  volIdx: 4, added: '2026-04-20' },
  { title: "As Time Goes On (Chill)",           file: "As Time Goes On (Chill).mp3",            lang: 'en',  volIdx: 4 },
  { title: "You Are The Word 2 (Bossa)",        file: "You Are The Word 2 (Bossa).mp3",         lang: 'en',  volIdx: 4, added: '2026-07-10' },
  { title: "You Are The Word 4 (Bossa)",        file: "You Are The Word 4 (Bossa).mp3",         lang: 'en',  volIdx: 4, added: '2026-07-10' },
  { title: "Every Season (Duet 2)",             file: "Every Season (Duet 2).mp3",              lang: 'en',  volIdx: 4, added: '2026-07-11' },
  { title: "Like A Rose (Bossa)",               file: "Like A Rose (Bossa).mp3",                lang: 'en',  volIdx: 4, added: '2026-07-12' },

  // ── (former Good Times — distributed) ────────────────────────
  { title: "Baka Ang Happy Ending",             file: "Baka Ang Happy Ending.mp3",              lang: 'tl',  volIdx: 1 },
  { title: "Baka Ang Saya",                     file: "Baka Ang Saya.mp3",                      lang: 'tl',  volIdx: 1 },
  { title: "Domestic Hustle",                   file: "Domestic Hustle.mp3",                    lang: 'en',  volIdx: 0 },
  { title: "Finally Home",                      file: "Finally Home.mp3",                       lang: 'en',  volIdx: 3 },
  { title: "Just You And Me",                   file: "Just You And Me.mp3",                    lang: 'en',  volIdx: 3 },
  { title: "My Grumpy, Old Honey",              file: "My Grumpy, Old Honey.mp3",               lang: 'en',  volIdx: 5 },
  { title: "Staycation Lang",                   file: "Staycation Lang.mp3",                    lang: 'tl',  volIdx: 1 },
  { title: "Staycation (R&B Funky)",            file: "Staycation (R&B Funky).mp3",             lang: 'tl',  volIdx: 1 },
  { title: "With You (Chill)",                  file: "With You (Chill).mp3",                   lang: 'en',  volIdx: 1, added: '2026-04-10' },
  { title: "Thank You, My Love",                file: "Thank You, My Love.mp3",                 lang: 'en',  volIdx: 3 },
  { title: "Thank You, My Love (Retro-Soul)",   file: "Thank You, My Love (Retro-Soul).mp3",    lang: 'en',  volIdx: 4 },
  { title: "This Time We're Staying",           file: "This Time We're Staying.mp3",            lang: 'en',  volIdx: 0 },
  { title: "In the Quiet Between Us",           file: "In the Quiet Between Us.mp3",            lang: 'en',  volIdx: 3 },
  { title: "In the Quiet Between Us (Bachata)", file: "In the Quiet Between Us (Bachata).mp3",  lang: 'en',  volIdx: 0 },
  { title: "Steady Hearts",                     file: "Steady Hearts.mp3",                      lang: 'en',  volIdx: 3 },
  { title: "Under This Umbrella",               file: "Under This Umbrella.mp3",                lang: 'en',  volIdx: 3 },
  { title: "You Are My Everything",             file: "You Are My Everything.mp3",              lang: 'en',  volIdx: 3 },
  { title: "With You (Pop-Rock)",               file: "With You (Pop-Rock).mp3",                lang: 'en',  volIdx: 3, added: '2026-04-10' },

  // ── Vol 9: Sundries ────────────────────────────────────────────
  { title: "Barkada",                           file: "Barkada.mp3",                            lang: 'tl',  volIdx: 5 },
  { title: "Barkada (Ver 2)",                   file: "Barkada (Ver 2).mp3",                    lang: 'tl',  volIdx: 5 },
  { title: "Panay Panalangin",                  file: "Panay Panalangin.mp3",                   lang: 'tl',  volIdx: 5 },
  { title: "Ako'y Lalaban",                     file: "Ako'y Lalaban.mp3",                      lang: 'tl',  volIdx: 5 },
  { title: "Steady Ascent",                     file: "Steady Ascent.mp3",                      lang: 'en',  volIdx: 5 },
  { title: "Steady Ascent (Indie Pop)",          file: "Steady Ascent (Indie Pop).mp3",          lang: 'en',  volIdx: 5 },
  { title: "Steady Ascent (Rock)",              file: "Steady Ascent (Rock).mp3",               lang: 'en',  volIdx: 5 },
  { title: "Trading Ice for Rain",              file: "Trading Ice for Rain.mp3",               lang: 'en',  volIdx: 5 },
  { title: "Trading Ice for Rain (R&B)",        file: "Trading Ice for Rain (R&B).mp3",         lang: 'en',  volIdx: 5 },
  { title: "Tropical Home",                      file: "Tropical Home.mp3",                      lang: 'en',  volIdx: 5, added: '2026-04-03' },
  { title: "Lost In The Beat",                  file: "Lost In The Beat.mp3",                   lang: 'en',  volIdx: 4, added: '2026-04-01' },
  { title: "Lost In The Beat (Disco)",          file: "Lost In The Beat (Disco).mp3",           lang: 'en',  volIdx: 0, added: '2026-04-01' },
  { title: "Lost In The Beat (R&B-Pop)",        file: "Lost In The Beat (R&B-Pop).mp3",         lang: 'en',  volIdx: 0, added: '2026-04-01' },
];
